=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Buildings.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="OrientalEmpires" xmlns:oe="OrientalEmpires" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:include schemaLocation="Requirement.xsd"/>

  <!-- Enumeration of external placement -->
  <xs:simpleType name="ExternalPlacementType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Normal"/>
      <xs:enumeration value="Shore"/>
      <xs:enumeration value="PlacementDot"/>
    </xs:restriction>
  </xs:simpleType>
  
  
  <xs:complexType name="Building">
    <xs:sequence>
      <xs:choice>
        <xs:element name="Model">
          <xs:complexType>
            <xs:sequence>
            <xs:element name="Prefab" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="Name" type="xs:string" use="required"/>
                <xs:attribute name="Style" type="xs:string" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="ShorePlacement" minOccurs="0">
              <xs:complexType>
                <xs:attribute name="Parameter" type="xs:float" use="optional"/>
                <xs:attribute name="FixedHeight" type="xs:float" use="optional"/>
              </xs:complexType>
            </xs:element>
              <xs:element name="Placement" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="R" type="xs:int" use ="required"/>
                  <xs:attribute name="G" type="xs:int" use ="required"/>
                  <xs:attribute name="B" type="xs:int" use ="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="SlotSize" type="xs:int" use="optional"/>
            <xs:attribute name="TempleSlot" type="xs:boolean" use="optional"/>
            <xs:attribute name="PalaceSlot" type="xs:boolean" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="VirtualBuilding">
          <xs:complexType>
            <xs:attribute name="Type" type="xs:string" use="optional"/>
            <xs:attribute name="Level" type="xs:int" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:choice>
      
      <xs:element name="Construction">
        <xs:complexType>
          <xs:attribute name="Cost" type="xs:int" use="required"/>
          <xs:attribute name="SackValue" type="xs:int" use="optional"/>
          <xs:attribute name="MinTurns" type="xs:int" use="required"/>
          <xs:attribute name="Upkeep" type="xs:int" use="required"/>
          <xs:attribute name="CardIcon" type="xs:string" use="required"/>
          <xs:attribute name="CardMinorIcon" type="xs:string" use="required"/>
          <xs:attribute name="Military" type="xs:boolean" use="optional"/>
        </xs:complexType>
      </xs:element>
      <!--Requirements that the player can take action to meet-->
      <xs:element name="Requirements" type="oe:RequirementList" minOccurs ="0"/>

      <!-- These are requirements that won't change over time, or are only valid
			at certain fixed locations. Player's won't be offerred items that don't meet
			the static reqirements since they have no means to meet them.
			Examples include requirements for a specific race, game type,
			or geographical location -->
      <xs:element name="StaticRequirements" type="oe:RequirementList" minOccurs ="0"/>

      <!-- The capabilities the building has -->
      <xs:element name="Capability" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType>
          <xs:attribute name="Name" type="xs:string" use="required"/>
          <xs:attribute name="Level" type="xs:int" use="required"/>
        </xs:complexType>
      </xs:element>

    </xs:sequence>
    <xs:attribute name="ID" type="xs:string" use="required"/>
    <xs:attribute name ="InSettlement" type="xs:boolean" use="required"/>
    <xs:attribute name="MaxNumber" type="xs:nonNegativeInteger" use="optional"/>
    <xs:attribute name ="Upgrades" type="xs:string" use="optional"/>
    <xs:attribute name ="Tags" type="xs:string" use="optional"/>
    <xs:attribute name="AllowedForHorde" type ="xs:boolean" use="optional"/>
  </xs:complexType>

  <!-- Modding Elements //////////////////////////////////////////////// -->

  <xs:complexType name="DropBuildingType">
    <xs:attribute name="ID" type="xs:string" use="required"/>
  </xs:complexType>

  <!--///////////////////////////////////////////////////////////////// -->

  <xs:element name="Root">
    <xs:complexType>
      <xs:choice>
        <xs:element name="Building" type="oe:Building" maxOccurs="unbounded"/>
        <xs:element name="Replace" type="oe:Building" maxOccurs="unbounded"/>
        <xs:element name="Drop" type="oe:DropBuildingType" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:complexType>

  </xs:element>
</xs:schema>

=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Buildings.xml
<?xml version="1.0" encoding="utf-8"?>
<Root xmlns="OrientalEmpires" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="OrientalEmpires Buildings.xsd">
  <!-- In settlement buildings /////////////////////////////////////////////////////////////////-->
  <!-- Shared Buildings Needs Description -->
  <!-- Temples Partly done Needs Description 
  
  Except for artillery peasant unrest/happiness should be pretty solid-->
  <!-- 
    (doesn't work, applies a static -90 instead of what it says ingame, -90%
  <Building ID="LaborReduction" InSettlement="true" MaxNumber="1" AllowedForHorde="true">
    <Model SlotSize="1" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_ChineseMarket_Lvl1" />
      <Prefab Style="Central Asian" Name="Architecture/Buildings/Prefabs/OE_Tech_CentralAsiaMarket_Lvl1" />
    </Model>
    <Construction Cost="0" SackValue="0" MinTurns="0" Upkeep="0" CardIcon="G_TechIcon_Agriculture_01" CardMinorIcon="G_Icon12x12_Market_01" />
    <Requirements>
      <Population Num="200" Condition="false" />
    </Requirements>
    <Capability Name="Peasant Unrest" Level="-90" />
  </Building> -->
  <Building ID="Buddhist Temple" InSettlement="true" Tags="Buddhist" AllowedForHorde="true">
    <Model SlotSize="2" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_ChineseTemple_Lvl1" />
    </Model>
    <Construction Cost="10000" SackValue="2500" MinTurns="0" Upkeep="200" CardIcon="G_BuildingIcon_TempleBuddhistLvl1_01" CardMinorIcon="G_Icon12x12_TempleBuddhist_01" />
    <Requirements>
      <Population Num="300" />
      <Tech Item="Buddhism" />
    </Requirements>
    <Capability Name="Peasant Happiness" Level="10" />
    <Capability Name="Noble Happiness" Level="5" />
    <Capability Name="Culture VP" Level="1" />
  </Building>
  <Building ID="Buddhist Temple II" InSettlement="true" Upgrades="Buddhist Temple" Tags="Buddhist">
    <Model SlotSize="2" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_ChineseTemple_Lvl2" />
    </Model>
    <Construction Cost="15000" SackValue="3750" MinTurns="0" Upkeep="400" CardIcon="G_BuildingIcon_TempleBuddhistLvl2_01" CardMinorIcon="G_Icon12x12_TempleBuddhist_01" />
    <Requirements>
      <Population Num="425" />
    </Requirements>
    <Capability Name="Peasant Happiness" Level="20" />
    <Capability Name="Noble Happiness" Level="10" />
    <Capability Name="Culture VP" Level="2" />
  </Building>
  <Building ID="Buddhist Temple III" InSettlement="true" Upgrades="Buddhist Temple II" Tags="Buddhist">
    <Model SlotSize="3" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_ChineseTemple_Lvl3" />
    </Model>
    <Construction Cost="20000" SackValue="5000" MinTurns="1" Upkeep="800" CardIcon="G_BuildingIcon_TempleBuddhistLvl3_01" CardMinorIcon="G_Icon12x12_TempleBuddhist_01" />
    <Requirements>
      <Population Num="550" />
    </Requirements>
    <Capability Name="Peasant Happiness" Level="30" />
    <Capability Name="Noble Happiness" Level="15" />
    <Capability Name="Culture VP" Level="3" />
  </Building>
  <Building ID="Taoist Temple" InSettlement="true" Tags="Taoist" AllowedForHorde="true">
    <Model SlotSize="2" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_TaoistTemple_Lvl1" />
    </Model>
    <Construction Cost="10000" SackValue="2500" MinTurns="0" Upkeep="200" CardIcon="G_BuildingIcon_TempleTaoistLvl1_01" CardMinorIcon="G_Icon12x12_TempleTaoist_01" />
    <Requirements>
      <Population Num="275" />
      <Tech Item="Daoism" />
    </Requirements>
    <Capability Name="Peasant Happiness" Level="5" />
    <Capability Name="Noble Happiness" Level="10" />
    <Capability Name="Boost Knowledge" Level="3" />
    <Capability Name="Culture VP" Level="1" />
  </Building>
  <Building ID="Taoist Temple II" InSettlement="true" Upgrades="Taoist Temple" Tags="Taoist">
    <Model SlotSize="2" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_TaoistTemple_Lvl2" />
    </Model>
    <Construction Cost="15000" SackValue="3750" MinTurns="0" Upkeep="400" CardIcon="G_BuildingIcon_TempleTaoistLvl2_01" CardMinorIcon="G_Icon12x12_TempleTaoist_01" />
    <Requirements>
      <Population Num="400" />
    </Requirements>
    <Capability Name="Peasant Happiness" Level="10" />
    <Capability Name="Noble Happiness" Level="15" />
    <Capability Name="Boost Knowledge" Level="6" />
    <Capability Name="Culture VP" Level="2" />
  </Building>
  <Building ID="Taoist Temple III" InSettlement="true" Upgrades="Taoist Temple II" Tags="Taoist">
    <Model SlotSize="3" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_TaoistTemple_Lvl3" />
    </Model>
    <Construction Cost="20000" SackValue="5000" MinTurns="1" Upkeep="800" CardIcon="G_BuildingIcon_TempleTaoistLvl3_01" CardMinorIcon="G_Icon12x12_TempleTaoist_01" />
    <Requirements>
      <Population Num="525" />
    </Requirements>
    <Capability Name="Peasant Happiness" Level="15" />
    <Capability Name="Noble Happiness" Level="20" />
    <Capability Name="Boost Knowledge" Level="12" />
    <Capability Name="Culture VP" Level="2" />
  </Building>
  <Building ID="Confucian Temple" InSettlement="true" Tags="Confucian" AllowedForHorde="true">
    <Model SlotSize="2" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_ConfucianTemple_Lvl1" />
    </Model>
    <Construction Cost="10000" SackValue="2500" MinTurns="01" Upkeep="200" CardIcon="G_BuildingIcon_TempleConfucianLvl1_01" CardMinorIcon="G_Icon12x12_TempleConfucian_01" />
    <Requirements>
      <Population Num="275" />
      <Tech Item="Confucianism" />
    </Requirements>
    <Capability Name="Peasant Happiness" Level="5" />
    <Capability Name="Noble Happiness" Level="10" />
    <Capability Name="Boost Craft" Level="3" />
    <Capability Name="Culture VP" Level="1" />
  </Building>
  <Building ID="Confucian Temple II" InSettlement="true" Upgrades="Confucian Temple" Tags="Confucian">
    <Model SlotSize="2" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_ConfucianTemple_Lvl2" />
    </Model>
    <Construction Cost="15000" SackValue="3750" MinTurns="0" Upkeep="400" CardIcon="G_BuildingIcon_TempleConfucianLvl2_01" CardMinorIcon="G_Icon12x12_TempleConfucian_01" />
    <Requirements>
      <Population Num="400" />
    </Requirements>
    <Capability Name="Peasant Happiness" Level="7" />
    <Capability Name="Noble Happiness" Level="20" />
    <Capability Name="Boost Craft" Level="6" />
    <Capability Name="Culture VP" Level="2" />
  </Building>
  <Building ID="Confucian Temple III" InSettlement="true" Upgrades="Confucian Temple II" Tags="Confucian">
    <Model SlotSize="3" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_ConfucianTemple_Lvl3" />
    </Model>
    <Construction Cost="20000" SackValue="5000" MinTurns="1" Upkeep="800" CardIcon="G_BuildingIcon_TempleConfucianLvl3_01" CardMinorIcon="G_Icon12x12_TempleConfucian_01" />
    <Requirements>
      <Population Num="525" />
    </Requirements>
    <Capability Name="Peasant Happiness" Level="10" />
    <Capability Name="Noble Happiness" Level="30" />
    <Capability Name="Boost Craft" Level="12" />
    <Capability Name="Culture VP" Level="3" />
  </Building>
  <Building ID="Mohist School" InSettlement="true" AllowedForHorde="true">
    <Model SlotSize="2" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_MohistSchool_Lvl1" />
    </Model>
    <Construction Cost="10000" SackValue="2500" MinTurns="0" Upkeep="200" CardIcon="G_BuildingIcon_MohistSchoolLvl1_01" CardMinorIcon="G_Icon12x12_MohistSchool_01" />
    <Requirements>
      <Population Num="275" />
      <Tech Item="Mohism" />
    </Requirements>
    <Capability Name="Peasant Happiness" Level="10" />
    <Capability Name="Noble Happiness" Level="5" />
    <Capability Name="Boost Thought" Level="3" />
    <Capability Name="Culture VP" Level="1" />
  </Building>
  <Building ID="Mohist School II" InSettlement="true" Upgrades="Mohist School">
    <Model SlotSize="2" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_MohistSchool_Lvl2" />
    </Model>
    <Construction Cost="15000" SackValue="3750" MinTurns="0" Upkeep="400" CardIcon="G_BuildingIcon_MohistSchoolLvl2_01" CardMinorIcon="G_Icon12x12_MohistSchool_01" />
    <Requirements>
      <Population Num="400" />
    </Requirements>
    <Capability Name="Peasant Happiness" Level="20" />
    <Capability Name="Noble Happiness" Level="7" />
    <Capability Name="Boost Thought" Level="6" />
    <Capability Name="Culture VP" Level="2" />
  </Building>
  <Building ID="Mohist School III" InSettlement="true" Upgrades="Mohist School II">
    <Model SlotSize="3" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_MohistSchool_Lvl3" />
    </Model>
    <Construction Cost="20000" SackValue="5000" MinTurns="1" Upkeep="800" CardIcon="G_BuildingIcon_MohistSchoolLvl3_01" CardMinorIcon="G_Icon12x12_MohistSchool_01" />
    <Requirements>
      <Population Num="525" />
    </Requirements>
    <Capability Name="Peasant Happiness" Level="30" />
    <Capability Name="Noble Happiness" Level="10" />
    <Capability Name="Boost Thought" Level="12" />
    <Capability Name="Culture VP" Level="3" />
  </Building>
  <Building ID="Legalist School" InSettlement="true">
    <Model SlotSize="1" TempleSlot="true">
      <Prefab Name="Architecture/Buildings/Prefabs/OE_Tech_ChineseLegalistSchool_Lvl1" />
    </Model>
    <Construction Cost="10000" SackValue="2500" MinTurns="1" Upkeep="0" CardIcon="G_BuildingIcon_LegalistSchoolLvl1_01" CardMinorIcon="G_Icon12x12_LegalistSchool_01" />
    <Requirements>
