=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Edicts.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="OrientalEmpires" xmlns:oe="OrientalEmpires" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:include schemaLocation="Requirement.xsd" />
  <xs:include schemaLocation="OECommon.xsd" />

  <xs:simpleType name="EdictEffect">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Cost" />
      <xs:enumeration value="PeasantUnrest" />
      <xs:enumeration value="NobleUnrest" />
      <xs:enumeration value="FoodProduction" />
      <xs:enumeration value="Culture" />
      <xs:enumeration value="Authority" />
      <xs:enumeration value="Trade" />
      <xs:enumeration value="BattleMorale" />
      <xs:enumeration value="MilitiaAvailability" />
      <xs:enumeration value="MilitiaSkill" />
      <xs:enumeration value="GarrissonAvailability" />
      <xs:enumeration value="Militia Melee LongSkill" />
      <xs:enumeration value="CollectAgricultureTax" />
      <!-- Leader Set value for type  0 = random, 1 = general, 2 = admin-->
      <xs:enumeration value="AddLeader" />
      <xs:enumeration value="TaxCollection" />
      <xs:enumeration value="SpecialPopulationTax" />
      <xs:enumeration value="AdvanceEra" />
      <xs:enumeration value="Recruitment" />
      <xs:enumeration value="Income" />
      <xs:enumeration value="ImmediateIncome" />
      <xs:enumeration value="PersonalAuthority" />
      <xs:enumeration value="DisasterUnrest" />
      <xs:enumeration value="RecruitSpecialUnits" />
      <xs:enumeration value="MoveCapital" />
      <xs:enumeration value="IncreaseBooty" />
      <xs:enumeration value="CancelDistancePenalty" />
      <xs:enumeration value="CancelSuccessionPenalty" />
      <xs:enumeration value="CreateOffice" />
      <xs:enumeration value="DestroySettlement" />
      <xs:enumeration value="MoveCapitalTo" />
      <xs:enumeration value="CreateUnit" />
      <xs:enumeration value="KillPuppetEmperor" />
      <xs:enumeration value="ReduceCorruption" />
      <xs:enumeration value="UpsetCourt" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="Effect">
    <xs:attribute name="Type" type="oe:EdictEffect" use="required" />
    <xs:attribute name="Value" type="xs:float" use="required" />
    <xs:attribute name="Name" type="xs:string" use="optional" />
    <xs:attribute name="Turns" type="xs:nonNegativeInteger" use="optional" />
    <xs:attribute name="PerTurn" type="xs:boolean" use="optional" />
  </xs:complexType>

  <!-- Definition for a single edict -->
  <xs:complexType name="Edict">
    <xs:sequence>
      <!--Requirements that the player can take action to meet-->
      <xs:element name="Requirements" type="oe:RequirementList" minOccurs="0" />

      <!-- These are requirements that won't change over time, or are only valid
			at certain fixed locations. Player's won't be offerred items that don't meet
			the static reqirements since they have no means to meet them.
			Examples include requirements for a specific race, game type,
			or geographical location -->
      <xs:element name="StaticRequirements" type="oe:RequirementList" minOccurs="0" />

      <xs:element name="Effect" type="oe:Effect" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="CancelEffect" type="oe:Effect" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="CancelsEdict" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType>
          <xs:attribute name="Name" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:string" use="required"></xs:attribute>
    <xs:attribute name="Area" type="oe:TechEdictArea" use="required"></xs:attribute>
    <xs:attribute name="NumTurns" type="xs:nonNegativeInteger" use="optional"></xs:attribute>
    <xs:attribute name="MayBeCancelled" type="xs:boolean" use="optional"></xs:attribute>
    <xs:attribute name="ExpireSilently" type="xs:boolean" use="optional"></xs:attribute>
    <xs:attribute name="LeaderTitle" type="xs:string" use="optional"></xs:attribute>
    <xs:attribute name="IssuedInStartingEra" type="xs:int" use="optional" />
    <xs:attribute name="TranslationTag" type="xs:string" use="optional" />
  </xs:complexType>

  <!-- Modding Elements //////////////////////////////////////////////////// -->

  <xs:complexType name="DropEdictType">
    <xs:attribute name="ID" type="xs:string" use="required" />
  </xs:complexType>

  <!-- ///////////////////////////////////////////////////////////////////// -->

  <xs:element name="Root">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="Edict" type="oe:Edict" maxOccurs="unbounded" />
        <xs:element name="Drop" type="oe:DropEdictType" />
        <xs:element name="Replace" type="oe:Edict" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Edicts.xml
<?xml version="1.0" encoding="utf-8"?>
<Root xmlns="OrientalEmpires" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="OrientalEmpires Edicts.xsd">


  <Edict ID="Self Criticism" Area="Misc" NumTurns="20" MayBeCancelled="false">
    <Requirements>
      <ControlNumSettlements Num="50" Exact="false" />
      <Tech Item="Mandate of Heaven2" />
      <SettlementWithDisasterUnrest />
    </Requirements>
    <Effect Type="Cost" Value="1000" />
    <Effect Type="PersonalAuthority" Value="-2" />
    <Effect Type="DisasterUnrest" Value="0" />
  </Edict>
  <Edict ID="Move Capital" Area="Misc" NumTurns="10" ExpireSilently="true" MayBeCancelled="false">
    <Requirements>
      <ControlNumSettlements Num="50" Exact="false" />
      <Tech Item="Priest King" />
      <CanRelocateCapital />
    </Requirements>
    <Effect Type="Cost" Value="500" />
    <Effect Type="MoveCapital" Value="0" />
    <Effect Type="NobleUnrest" Value="15" Turns="10" />
  </Edict>
  <Edict ID="Ride Like a Barbarian" Area="Military">
    <Requirements>
      <ControlNumSettlements Num="25" Exact="false" />
      <Tech Item="Horse Archery" />
      <Edict Item="Gentlemen Ride Horses" />
    </Requirements>
    <StaticRequirements>
      <Faction ID="Zhao" />
    </StaticRequirements>
    <Effect Type="Cost" Value="1000" />
    <Effect Type="RecruitSpecialUnits" Value="0" />
    <Effect Type="NobleUnrest" Value="15" Turns="20" />
    <CancelEffect Type="Authority" Value="-3" Turns="20" />
  </Edict>
  <Edict ID="Kurultai" Area="Authority" NumTurns="2" ExpireSilently="true" MayBeCancelled="false">
    <Requirements>
      <ControlNumSettlements Num="25" Exact="false" />
      <Tech Item="Kurultai" />
      <SuccessionCrisis />
      <FactionLeaderInCapital />
    </Requirements>
    <Effect Type="Cost" Value="1000" />
    <Effect Type="CancelSuccessionPenalty" Value="10" />
    <Effect Type="PersonalAuthority" Value="1" />
  </Edict>
  <Edict ID="Great Kurultai" Area="Authority" MayBeCancelled="false">
    <Requirements>
      <ControlNumSettlements Num="25" Exact="false" />
      <ScriptEventTriggered Event="Genghis Khan" />
      <FactionLeaderInCapital />
    </Requirements>
    <StaticRequirements>
      <FactionTag Tag="Genghis" />
    </StaticRequirements>
    <Effect Type="Cost" Value="1000" />
    <Effect Type="PersonalAuthority" Value="8" />
  </Edict>
  <Edict ID="Establish Keshik" Area="Military" MayBeCancelled="false">
    <Requirements>
      <ControlNumSettlements Num="25" Exact="false" />
      <Edict Item="Great Kurultai" />
    </Requirements>
    <StaticRequirements>
      <FactionTag Tag="Genhis" />
    </StaticRequirements>
    <Effect Type="RecruitSpecialUnits" Value="0" />
    <Effect Type="Cost" Value="1000" />
  </Edict>
  <Edict ID="Yassa Law" Area="Authority">
    <Requirements>
      <ControlNumSettlements Num="25" Exact="false" />
      <Tech Item="Khanate Administration" />
    </Requirements>
    <Effect Type="Cost" Value="200" PerTurn="true" />
    <Effect Type="Authority" Value="2" />
    <Effect Type="PeasantUnrest" Value="-10" />
    <CancelEffect Type="PeasantUnrest" Value="20" Turns="20" />
  </Edict>
  <Edict ID="Freedom of Worship" Area="Culture">
    <Requirements>
      <ControlNumSettlements Num="25" Exact="false" />
      <Tech Item="Khanate Administration" />
    </Requirements>
    <Effect Type="Cost" Value="200" />
    <Effect Type="Culture" Value="2" />
    <Effect Type="PeasantUnrest" Value="-10" />
    <CancelEffect Type="PeasantUnrest" Value="20" Turns="20" />
  </Edict>
  <Edict ID="Grand Commandant New" Area="Military" TranslationTag="Grand Commandant">
    <Requirements>
      <ControlNumSettlements Num="15" Exact="false" />
    </Requirements>
    <StaticRequirements>
      <UsingRoyalCourt />
    </StaticRequirements>
    <!-- Value 1 = general-->
    <Effect Type="AddLeader" Value="1" />
    <Effect Type="Authority" Value="-1" />
    <Effect Type="Cost" Value="80" PerTurn="true" />
    <Effect Type="CreateOffice" Name="Grand Commandant" Value="0" />
    <CancelEffect Type="Authority" Value="-1" Turns="20" />
  </Edict>
  <Edict ID="Central Bureaucracy New" Area="Authority" LeaderTitle="ELDR Chancellor" TranslationTag="Central Bureaucracy">
    <Requirements>
      <ControlNumSettlements Num="15" Exact="false" />
      <Tech Item="Bamboo Strips" />
    </Requirements>
    <StaticRequirements>
      <UsingRoyalCourt />
    </StaticRequirements>
    <Effect Type="CreateOffice" Name="Grand Chancellor" Value="0" />
    <!-- Value 2 = admin-->
    <Effect Type="AddLeader" Value="2" />
    <Effect Type="PeasantUnrest" Value="-10" />
    <Effect Type="Authority" Value="2" />
    <Effect Type="Cost" Value="400" PerTurn="true" />
    <Effect Type="NobleUnrest" Value="25" Turns="20" />
    <CancelEffect Type="Authority" Value="-1" Turns="20" />
  </Edict>
  <Edict ID="The Three Excellencies" Area="Authority">
    <Requirements>
      <ControlNumSettlements Num="100" Exact="false" />
      <Edict Item="Central Bureaucracy New" />
      <Edict Item="Grand Commandant New" />
    </Requirements>
    <StaticRequirements>
      <UsingRoyalCourt />
    </StaticRequirements>
    <Effect Type="CreateOffice" Name="Imperial Counsellor" Value="0" />
    <Effect Type="Authority" Value="1" />
    <Effect Type="Cost" Value="100" PerTurn="true" />
    <Effect Type="NobleUnrest" Value="10" Turns="20" />
    <CancelEffect Type="Authority" Value="-1" Turns="20" />
  </Edict>
  <Edict ID="Minister Coachman" Area="Authority">
    <Requirements>
      <ControlNumSettlements Num="25" Exact="false" />
      <Tech Item="Light Chariot" />
    </Requirements>
    <StaticRequirements>
      <UsingRoyalCourt />
    </StaticRequirements>
    <Effect Type="CreateOffice" Name="Minister Coachman" Value="0" />
    <Effect Type="Authority" Value="1" />
    <Effect Type="Cost" Value="60" PerTurn="true" />
    <CancelEffect Type="Authority" Value="-1" Turns="20" />
  </Edict>
  <Edict ID="Centralized Justice" Area="Authority">
    <Requirements>
      <ControlNumSettlements Num="50" Exact="false" />
      <Tech Item="Five Punishments" />
    </Requirements>
    <StaticRequirements>
      <UsingRoyalCourt />
    </StaticRequirements>
    <Effect Type="CreateOffice" Name="Minister of Justice" Value="0" />
    <Effect Type="Authority" Value="1" />
    <Effect Type="Cost" Value="100" PerTurn="true" />
    <CancelEffect Type="PeasantUnrest" Value="15" Turns="20" />
  </Edict>
  <Edict ID="Centralized Rites" Area="Culture">
    <Requirements>
      <ControlNumSettlements Num="75" Exact="false" />
      <Tech Item="Imperial Rites" />
    </Requirements>
    <StaticRequirements>
      <UsingRoyalCourt />
    </StaticRequirements>
    <Effect Type="CreateOffice" Name="Minister of Rites" Value="0" />
    <Effect Type="Culture" Value="1" />
    <Effect Type="Cost" Value="80" PerTurn="true" />
    <CancelEffect Type="Authority" Value="-2" Turns="10" />
  </Edict>
  <Edict ID="The Six Ministries" Area="Authority">
    <Requirements>
      <ControlNumSettlements Num="50" Exact="false" />
      <Tech Item="Paper" />
      <Edict Item="The Three Excellencies" />
    </Requirements>
    <StaticRequirements>
      <UsingRoyalCourt />
    </StaticRequirements>
    <Effect Type="CreateOffice" Name="Minister oF War" Value="0" />
    <Effect Type="CreateOffice" Name="Minister oF Finance" Value="0" />
    <Effect Type="CreateOffice" Name="Minister of Works" Value="0" />
    <Effect Type="CreateOffice" Name="Minister of Rites" Value="0" />
    <Effect Type="CreateOffice" Name="Minister of Justice" Value="0" />
    <Effect Type="CreateOffice" Name="Minister of Personnel" Value="0" />
    <Effect Type="Authority" Value="8" />
    <Effect Type="Cost" Value="500" PerTurn="true" />
    <Effect Type="NobleUnrest" Value="15" Turns="20" />
    <CancelEffect Type="Authority" Value="-4" Turns="20" />
    <CancelsEdict Name="Grand Commandant New" />
    <CancelsEdict Name="Central Bureaucracy New" />
    <CancelsEdict Name="The Three Excellencies" />
    <CancelsEdict Name="Minister Coachman" />
  </Edict>
  <Edict ID="Appoint a Shi New" Area="Military" TranslationTag="Appoint a Shi">
    <Requirements>
      <ControlNumSettlements Num="50" Exact="false" />
      <Tech Item="I Ching" />
    </Requirements>
    <StaticRequirements>
      <UsingRoyalCourt Condition="true" />
    </StaticRequirements>
    <!-- Value 2 = admin-->
    <Effect Type="CreateOffice" Value="0" Name="Advisor 1" />
    <Effect Type="NobleUnrest" Value="5" />
    <Effect Type="Cost" Value="30" PerTurn="true" />
    <Effect Type="Cost" Value="0" />
  </Edict>
  <Edict ID="Appoint a Strategist New" Area="Military" TranslationTag="Appoint a Strategist">
    <Requirements>
      <ControlNumSettlements Num="25" Exact="false" />
      <Tech Item="Military Theory" />
    </Requirements>
    <StaticRequirements>
      <UsingRoyalCourt Condition="true" />
    </StaticRequirements>
    <Effect Type="CreateOffice" Value="0" Name="Advisor 2" />
    <Effect Type="NobleUnrest" Value="5" />
    <Effect Type="Cost" Value="100" PerTurn="true" />
  </Edict>
  <Edict ID="Salt Tax New" Area="Economy" TranslationTag="Salt Tax">
    <Requirements>
      <Edict Item="Central Bureaucracy New" />
      <Tech Item="Coinage" />
      <Never />
    </Requirements>
    <StaticRequirements>
      <UsingRoyalCourt Condition="true" />
    </StaticRequirements>
    <Effect Type="NobleUnrest" Value="10" />
    <Effect Type="PeasantUnrest" Value="20" />
    <Effect Type="SpecialPopulationTax" Value="1" />
    <CancelEffect Type="Authority" Value="-1" Turns="20" />
  </Edict>
  <Edict ID="Private Land New" Area="Agriculture" TranslationTag="Private Land">
    <Requirements>
