=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Encounters.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="OrientalEmpires" xmlns:oe="OrientalEmpires" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:simpleType name="RewardType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="RandomPowerTech"/>
      <xs:enumeration value="ImprovePowerResearch"/>
      <xs:enumeration value="RandomCraftTech"/>
      <xs:enumeration value="ImproveCraftResearch"/>
      <xs:enumeration value="RandomThoughtTech"/>
      <xs:enumeration value="ImproveThoughtResearch"/>
      <xs:enumeration value="RandomKnowledgeTech"/>
      <xs:enumeration value="ImproveKnowledgeResearch"/>
      <xs:enumeration value="ImproveQi"/>
      <xs:enumeration value="ImproveRen"/>
      <xs:enumeration value="Money"/>
      <xs:enumeration value="IncreaseAuthority"/>

      <xs:enumeration value="DecreaeQi"/>
      <xs:enumeration value="DecreaseRen"/>
      <xs:enumeration value="DecreaseAuthority"/>
      <xs:enumeration value="RevealMap"/>
      <xs:enumeration value="RevealCities"/>
      <xs:enumeration value="RevealCapital"/>
      <xs:enumeration value="RevealWater"/>
      <xs:enumeration value="RevealResource"/>
      <xs:enumeration value="JoinAsMilitaryLeader"/>
      <xs:enumeration value="JoinAsCivilLeader"/>
      <xs:enumeration value="UnitsJoinArmy"/>
      <xs:enumeration value="CultureVPs"/>
      <xs:enumeration value="Never"/>
      <xs:enumeration value="Always"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CostType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Money"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!-- Standard Event Modifiers -->
  <xs:complexType name="ClimateModifier">
    <xs:attribute name="ID" type="xs:string" use="required"/>
    <xs:attribute name="Modifier" type="xs:float" use="required"/>
  </xs:complexType>

  <xs:complexType name="TerrainModifier">
    <xs:attribute name="BaseTerrainID" type="xs:string" use="required"/>
    <xs:attribute name="Modifier" type="xs:float" use="required"/>
  </xs:complexType>

  <xs:complexType name="TechModifier">
    <xs:attribute name="Item" type="xs:string" use="required"/>
    <xs:attribute name="Modifier" type="xs:float" use="required"/>
  </xs:complexType>

  <xs:complexType name="DifficultyModifier">
    <xs:attribute name="VH" type="xs:float" use="optional"/>
    <xs:attribute name="H" type="xs:float" use="optional"/>
    <xs:attribute name="N" type="xs:float" use="optional"/>
    <xs:attribute name="E" type="xs:float" use="optional"/>
  </xs:complexType>
   
  <xs:complexType name="Encounter">
    <xs:sequence>
      <xs:element name="Graphics">
        <xs:complexType>
          <xs:attribute name="Picture" type="xs:string" use ="required"/>
          <xs:attribute name="Portrait" type="xs:string" use ="required"/>
          <xs:attribute name="SpriteMarker" type="xs:string" use ="required"/>
          <xs:attribute name="EventIcon" type="xs:string" use ="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Occurance">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="AllowedTerrain" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="ID" type="xs:string" use ="required"/>
              </xs:complexType>
            </xs:element>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="ClimateModifier" type="oe:ClimateModifier" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="TerrainModifier" type="oe:TerrainModifier" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
          </xs:sequence>
          <xs:attribute name="BaseChance" type="xs:float" use ="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Rewards" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="Type" type="oe:RewardType" use="required"/>
          <xs:attribute name="Min" type="xs:float" use="required"/>
          <xs:attribute name="Max" type="xs:float" use="required"/>
          <xs:attribute name="Tag" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Cost" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="Type" type="oe:CostType" use="required"/>
          <xs:attribute name="Min" type="xs:float" use="required"/>
          <xs:attribute name="Max" type="xs:float" use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Text">
        <xs:complexType>
          <xs:attribute name="NoReward" type="xs:string" use ="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:string" use ="required"/>
    <xs:attribute name="PersistAfterFirstVisit" type="xs:int" use ="optional"/>
    <xs:attribute name="MustAccept" type="xs:boolean" use ="optional"/>
  </xs:complexType>
  
  <xs:element name="Root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Encounter" type="oe:Encounter" maxOccurs ="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Encounters.xml
<?xml version="1.0" encoding="utf-8"?>
<Root xmlns="OrientalEmpires"
xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation ="OrientalEmpires Encounters.xsd">

  <!-- Tech Encounters /////////////////////////////////////////////////-->
  <!-- Famous Craftsman -->
  <Encounter ID="CraftsmanA" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_03" Portrait="Character_07" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Grassland"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <!-- High random range for reward to span list of techs -->
    <Rewards Type="RandomCraftTech" Min="0" Max="10000"/>
    <Cost Type="Money" Min="50" Max="200"/>
    <Text NoReward="ENC Nothing To Teach"/>
  </Encounter>
  <Encounter ID="CraftsmanB" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_03" Portrait="Character_16" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Grassland"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <Rewards Type="ImproveCraftResearch" Min="5" Max="15"/>
    <Cost Type="Money" Min="250" Max="750"/>
    <Text NoReward="ENC Nothing To Teach"/>
  </Encounter>

  <!-- Famous Statesmen -->
  <Encounter ID="StatesmanA" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_10" Portrait="Character_06" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Grassland"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <!-- High random range for reward to span list of techs -->
    <Rewards Type="RandomPowerTech" Min="0" Max="10000"/>
    <Cost Type="Money" Min="100" Max="250"/>
    <Text NoReward="ENC Nothing To Teach"/>
  </Encounter>
  <Encounter ID="StatesmanB" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_11" Portrait="Character_09" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Grassland"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <Rewards Type="ImprovePowerResearch" Min="5" Max="15"/>
    <Cost Type="Money" Min="300" Max="900"/>
    <Text NoReward="ENC Nothing To Teach"/>
  </Encounter>
  <Encounter ID="StatesmanC" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_12" Portrait="Character_15" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Grassland"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <Rewards Type="JoinAsCivilLeader" Min="0" Max="0"/>
    <Cost Type="Money" Min="500" Max="1500"/>
    <Text NoReward="ENC Not Here"/>
  </Encounter>

  <!-- Famous Philosophers -->
  <Encounter ID="PhilosopherA" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_09" Portrait="Character_01" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Grassland"/>
      <AllowedTerrain ID="Gentle Hills"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0.1"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <!-- High random range for reward to span list of techs -->
    <Rewards Type="RandomThoughtTech" Min="0" Max="10000"/>
    <Text NoReward="ENC Nothing To Teach"/>
  </Encounter>
  <Encounter ID="PhilosopherB" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_12" Portrait="Character_12" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Grassland"/>
      <AllowedTerrain ID="Gentle Hills"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0.1"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <Rewards Type="ImproveThoughtResearch" Min="5" Max="15"/>
    <Cost Type="Money" Min="100" Max="300"/>
    <Text NoReward="ENC Nothing To Teach"/>
  </Encounter>

  <!-- Famous Scholars -->
  <Encounter ID="ScholarA" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_06" Portrait="Character_13" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Grassland"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <!-- High random range for reward to span list of techs -->
    <Rewards Type="RandomKnowledgeTech" Min="0" Max="10000"/>
    <Cost Type="Money" Min="200" Max="400"/>
    <Text NoReward="ENC Nothing To Teach"/>
  </Encounter>
  <Encounter ID="ScholarB" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_04" Portrait="Character_17" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Grassland"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <Rewards Type="ImproveKnowledgeResearch" Min="5" Max="15"/>
    <Cost Type="Money" Min="250" Max="750"/>
    <Text NoReward="ENC Nothing To Teach"/>
  </Encounter>

  <!-- Teachers -->
  <Encounter ID="TeacherA" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_01" Portrait="Character_09" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Grassland"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <Rewards Type="ImproveQi" Min="1" Max="2"/>
    <Cost Type="Money" Min="100" Max="300"/>
    <Text NoReward="ENC Nothing To Teach"/>
  </Encounter>
  <Encounter ID="TeacherB" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_06" Portrait="Character_06" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Grassland"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <Rewards Type="ImproveRen" Min="1" Max="2"/>
    <Cost Type="Money" Min="100" Max="300"/>
    <Text NoReward="ENC Nothing To Teach"/>
  </Encounter>
  <Encounter ID="TeacherC" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_09" Portrait="Character_19" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Grassland"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <Rewards Type="ImproveRen" Min="1" Max="1"/>
    <Text NoReward="ENC Nothing To Teach"/>
  </Encounter>

  <!-- Historians-->
  <Encounter ID="HistorianA" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_01" Portrait="Character_10" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Gentle Hills"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <Rewards Type="ImproveRen" Min="1" Max="2"/>
    <Cost Type="Money" Min="100" Max="300"/>
    <Text NoReward="ENC Nothing To Teach"/>
  </Encounter>

  <!-- Shaman / Witches-->
  <Encounter ID="WitchA" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_08" Portrait="Character_03" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Gentle Hills"/>
      <AllowedTerrain ID="Grassland"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0.1"/>
      <ClimateModifier ID="Central Asia" Modifier="0.5"/>
    </Occurance>
    <Rewards Type="IncreaseAuthority" Min="1" Max="2"/>
    <Cost Type="Money" Min="10" Max="200"/>
    <Text NoReward="ENC Only For Leader or Heir"/>
  </Encounter>

  <!-- Noble Women-->
  <Encounter ID="NoblewomanA" PersistAfterFirstVisit="10">
    <Graphics Picture="EncounterBG_11" Portrait="Character_05" SpriteMarker="G_Icon_Encounter_Default_01" EventIcon="G_Icon_List_EventEncounter_01"/>
    <Occurance BaseChance="0.0005">
      <AllowedTerrain ID="Fertile Plain"/>
      <AllowedTerrain ID="Gentle Hills"/>
      <ClimateModifier ID="Gobi Desert" Modifier="0"/>
