=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Events.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="OrientalEmpires" xmlns:oe="OrientalEmpires" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:simpleType name="TriggerTest">
    <xs:restriction base="xs:string">
      <xs:enumeration value="PerTurn"/>
      <xs:enumeration value="PerClimateRegion"/>
      <xs:enumeration value="PerSettlement"/>
      <xs:enumeration value="PerArmy"/>
      <xs:enumeration value="PerPlayer"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="EventTarget">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TriggerTarget"/>
      <xs:enumeration value="OneSettlement"/>
      <xs:enumeration value="AllSettlements"/>
      <xs:enumeration value="SettlementAndSettlementsNearby"/>
      <xs:enumeration value="SettlementsNearRiver"/>
      <xs:enumeration value="AllPlayers"/>
      <xs:enumeration value="RiverSection"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="EventEffect">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DamageBuildings"/>
      <xs:enumeration value="DamageWalls"/>
      <xs:enumeration value="KillPopulation"/>
      <xs:enumeration value="KillAnimals"/>
      <xs:enumeration value="KillSoldiers"/>
      <xs:enumeration value="SinkShips"/>
      <xs:enumeration value="KillCharacter"/>
      <xs:enumeration value="ArmyReadiness"/>
      <xs:enumeration value="PreventMovement"/>
      <xs:enumeration value="PeasantUnrest"/>
      <xs:enumeration value="NobleUnrest"/>
      <xs:enumeration value="GlobalPeasantUnrest"/>
      <xs:enumeration value="GlobalNobleUnrest"/>
      <xs:enumeration value="GrainProduction"/>      
    </xs:restriction>
  </xs:simpleType>

  <!-- Standard Event Modifiers -->
  <xs:complexType name="ClimateModifier">
    <xs:attribute name="ID" type="xs:string" use="required"/>
    <xs:attribute name="Modifier" type="xs:float" use="required"/>
  </xs:complexType>

  <xs:complexType name="TerrainModifier">
    <xs:attribute name="BaseTerrainID" type="xs:string" use="required"/>
    <xs:attribute name="Modifier" type="xs:float" use="required"/>
  </xs:complexType>

  <xs:complexType name="TechModifier">
    <xs:attribute name="Item" type="xs:string" use="required"/>
    <xs:attribute name="Modifier" type="xs:float" use="required"/>
  </xs:complexType>

  <xs:complexType name="ArmySizeModifier">
    <xs:attribute name="LessThan" type="xs:int" use="required"/>
    <xs:attribute name="Modifier" type="xs:float" use="required"/>
  </xs:complexType>

  <xs:complexType name="PopulationModifier">
    <xs:attribute name="LessThan" type="xs:int" use="required"/>
    <xs:attribute name="Modifier" type="xs:float" use="required"/>
  </xs:complexType>

  <xs:complexType name="DifficultyModifier">
    <xs:attribute name="VH" type="xs:float" use="optional"/>
    <xs:attribute name="H" type="xs:float" use="optional"/>
    <xs:attribute name="N" type="xs:float" use="optional"/>
    <xs:attribute name="E" type="xs:float" use="optional"/>
  </xs:complexType>
   
  <xs:complexType name="EventTrigger">
    <xs:sequence>
      <xs:element name="AIDifficultyModifier" type="oe:DifficultyModifier" minOccurs="0"/>
      <xs:element name="PlayerDifficultyModifier" type="oe:DifficultyModifier" minOccurs="0"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="ClimateModifier" type="oe:ClimateModifier" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="TechModifier" type="oe:TechModifier" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="ArmySizeModifier" type="oe:ArmySizeModifier" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="PopulationModifier" type="oe:PopulationModifier" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="TerrainModifier" type="oe:TerrainModifier" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice> 
    </xs:sequence>
    <xs:attribute name="Test" type="oe:TriggerTest" use ="required"/>
    <xs:attribute name="BaseChance" type="xs:float" use ="required"/>
    <xs:attribute name="MinTurnToOccur" type="xs:int" use ="optional"/>
  </xs:complexType>

  <xs:complexType name="EventEffectType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="ClimateModifier" type="oe:ClimateModifier" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="TechModifier" type="oe:TechModifier" minOccurs="0" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attribute name="Effect" type="oe:EventEffect" use="required"/>
    <xs:attribute name="Chance" type="xs:float" use ="optional"/>
    <xs:attribute name="Parameter" type="xs:int" use ="optional"/>
    <xs:attribute name="Duration" type="xs:int" use ="optional"/>
    <xs:attribute name="MinPercent" type="xs:float" use ="optional"/>
    <xs:attribute name="MaxPercent" type="xs:float" use ="optional"/>
  </xs:complexType>

  <xs:complexType name="EventTargetSelection">
    <xs:sequence>
      <xs:element name="AIDifficultyModifier" type="oe:DifficultyModifier" minOccurs="0"/>
      <xs:element name="PlayerDifficultyModifier" type="oe:DifficultyModifier" minOccurs="0"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="ClimateModifier" type="oe:ClimateModifier" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="TechModifier" type="oe:TechModifier" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="ArmySizeModifier" type="oe:ArmySizeModifier" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="PopulationModifier" type="oe:PopulationModifier" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="TerrainModifier" type="oe:TerrainModifier" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:element name ="Effect" type ="oe:EventEffectType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="Affects" type="oe:EventTarget" use="required"/>
    <xs:attribute name="Range" type="xs:int" use="optional"/>
  </xs:complexType>
  
  <xs:complexType name="Event">
    <xs:sequence>
      <xs:element name="Trigger" type="oe:EventTrigger"/>
      <xs:element name ="Target" type="oe:EventTargetSelection" maxOccurs="unbounded"/>
      <xs:element name ="ReportToPlayer">
        <xs:complexType>
          <xs:attribute name="EventName" type="xs:string" use="required"/>
          <xs:attribute name="MainMsg" type="xs:string" use="required"/>
          <xs:attribute name="MsgTitle" type="xs:string" use="optional"/>
          <xs:attribute name="SecondaryMsg" type="xs:string" use="optional"/>
          <xs:attribute name="OngoingMsg" type="xs:string" use="optional"/>
          <xs:attribute name="NoEffectMsg" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name ="ThirdPartyReport" minOccurs="0">
        <xs:complexType>
          <xs:attribute name="EventName" type="xs:string" use="required"/>
          <xs:attribute name="MsgTitle" type="xs:string" use="optional"/>
          <xs:attribute name="MainMsg" type="xs:string" use="required"/>
          <xs:attribute name="OngoingMsg" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:string" use ="required"/>
    <xs:attribute name="Picture" type="xs:string" use ="required"/>
    <xs:attribute name="PositiveEvent" type="xs:boolean" use ="optional"/>
  </xs:complexType>
  
  <xs:element name="Root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Event" type="oe:Event" maxOccurs ="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Events.xml
<?xml version="1.0" encoding="utf-8"?>
<Root xmlns="OrientalEmpires" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="OrientalEmpires Events.xsd">
  <Event ID="Labor Unrest Reduction" Picture="G_TechIcon_CropRotation_01" PositiveEvent="true">
    <Trigger Test="PerTurn" BaseChance="100" MinTurnToOccur="1">
      <ClimateModifier ID="Central Asia" Modifier="100" />
      <ClimateModifier ID="Gobi Desert" Modifier="100" />
      <ClimateModifier ID="Northern China" Modifier="100" />
      <ClimateModifier ID="Southern China" Modifier="100" />
      <ClimateModifier ID="Western China" Modifier="100" />
    </Trigger>
    <Target Affects="AllPlayers">
      <AIDifficultyModifier VH="0.8" H="0.9" />
      <PlayerDifficultyModifier E="1.1" />
      <PopulationModifier LessThan="10000" Modifier="1.5" />
      <PopulationModifier LessThan="4900" Modifier="3.0" />
      <PopulationModifier LessThan="4800" Modifier="3.05" />
      <PopulationModifier LessThan="4700" Modifier="3.1" />
      <PopulationModifier LessThan="4600" Modifier="3.15" />
      <PopulationModifier LessThan="4500" Modifier="3.2" />
      <PopulationModifier LessThan="4400" Modifier="3.25" />
      <PopulationModifier LessThan="4300" Modifier="3.3" />
      <PopulationModifier LessThan="4200" Modifier="3.35" />
      <PopulationModifier LessThan="4100" Modifier="3.4" />
      <PopulationModifier LessThan="4000" Modifier="3.45" />
      <PopulationModifier LessThan="3900" Modifier="3.55" />
      <PopulationModifier LessThan="3800" Modifier="3.65" />
      <PopulationModifier LessThan="3700" Modifier="3.75" />
      <PopulationModifier LessThan="3600" Modifier="3.85" />
      <PopulationModifier LessThan="3500" Modifier="3.95" />
      <PopulationModifier LessThan="3400" Modifier="4.1" />
      <PopulationModifier LessThan="3300" Modifier="4.25" />
      <PopulationModifier LessThan="3200" Modifier="4.4" />
      <PopulationModifier LessThan="3100" Modifier="4.55" />
      <PopulationModifier LessThan="3000" Modifier="4.7" />
      <PopulationModifier LessThan="2900" Modifier="4.85" />
      <PopulationModifier LessThan="2800" Modifier="5.0" />
      <PopulationModifier LessThan="2700" Modifier="5.1" />
      <PopulationModifier LessThan="2600" Modifier="5.2" />
      <PopulationModifier LessThan="2500" Modifier="5.3" />
      <PopulationModifier LessThan="2400" Modifier="5.4" />
      <PopulationModifier LessThan="2300" Modifier="5.5" />
      <PopulationModifier LessThan="2200" Modifier="5.6" />
      <PopulationModifier LessThan="2100" Modifier="5.7" />
      <PopulationModifier LessThan="2000" Modifier="5.8" />
      <PopulationModifier LessThan="1900" Modifier="5.9" />
      <PopulationModifier LessThan="1800" Modifier="6" />
      <PopulationModifier LessThan="1700" Modifier="5.9" />
      <PopulationModifier LessThan="1600" Modifier="5.8" />
      <PopulationModifier LessThan="1500" Modifier="5.5" />
      <PopulationModifier LessThan="1400" Modifier="5.2" />
      <PopulationModifier LessThan="1300" Modifier="4.9" />
      <PopulationModifier LessThan="1200" Modifier="4.6" />
      <PopulationModifier LessThan="1100" Modifier="4.3" />
      <PopulationModifier LessThan="1000" Modifier="4" />
      <PopulationModifier LessThan="900" Modifier="3.7" />
      <PopulationModifier LessThan="800" Modifier="3.4" />
      <PopulationModifier LessThan="700" Modifier="3.1" />
      <PopulationModifier LessThan="600" Modifier="2.8" />
      <PopulationModifier LessThan="500" Modifier="2.5" />
      <PopulationModifier LessThan="400" Modifier="2.2" />
      <PopulationModifier LessThan="300" Modifier="1.9" />
      <PopulationModifier LessThan="200" Modifier="1.6" />
      <PopulationModifier LessThan="100" Modifier="1.3" />
      <!-- <Effect Effect="PeasantUnrest" Parameter="-1"></Effect>
      <Effect Effect="GlobalPeasantUnrest" Parameter="-1"></Effect> -->
      <Effect Effect="PeasantUnrest" Parameter="-1" Duration="99999" MinPercent="-1" MaxPercent="100"></Effect>
      <Effect Effect="GlobalPeasantUnrest" Parameter="-1" Duration="99999" MinPercent="-1" MaxPercent="100"></Effect>
    </Target>
    <ReportToPlayer EventName="DS Labor Unrest Reduction Msg" MainMsg="DS Labor Unrest Reduction Text" />
  </Event>

  <!-- Disasters ////////////////////////////////////////////////////// -->
  <!-- Minor Earthquake -->
  <Event ID="Minor Earthquake" Picture="OE_Event_EarthQuake_01">
    <Trigger Test="PerClimateRegion" BaseChance="0.01" MinTurnToOccur="10">
      <!-- Modifiers to occurance chance -->
      <ClimateModifier ID="Central Asia" Modifier="0" />
      <ClimateModifier ID="Gobi Desert" Modifier="1" />
      <ClimateModifier ID="Northern China" Modifier="0.5" />
      <ClimateModifier ID="Southern China" Modifier="1.5" />
      <ClimateModifier ID="Western China" Modifier="2" />
    </Trigger>
    <Target Affects="OneSettlement">
      <!-- Modifiers to effects -->
      <AIDifficultyModifier VH="0.5" H="0.5" />
      <PlayerDifficultyModifier E="0.5" />
      <Effect Effect="DamageBuildings" Chance="0.4">
        <TechModifier Item="Ceramic Roof Tiles" Modifier="0.33" />
      </Effect>
      <Effect Effect="DamageWalls" Chance="0.2">
        <TechModifier Item="Brick Faced Walls" Modifier="0.5" />
      </Effect>
      <Effect Effect="KillPopulation" MinPercent="10" MaxPercent="25">
        <TechModifier Item="Ceramic Roof Tiles" Modifier="0.33" />
      </Effect>
      <Effect Effect="KillCharacter" Chance="0.1" />
      <Effect Effect="KillSoldiers" MinPercent="0" MaxPercent="20" />
      <Effect Effect="NobleUnrest" Parameter="10" Duration="3" />
      <Effect Effect="PeasantUnrest" Parameter="10" Duration="3" />
    </Target>
    <ReportToPlayer EventName="DS Earthquake Msg" MainMsg="DS Earthquake Text" />
    <ThirdPartyReport EventName="DS 3P Earthquake Msg" MainMsg="DS 3P Earthquake Text" />
  </Event>


  <!-- Major Earthquake -->
  <Event ID="Major Earthquake" Picture="OE_Event_EarthQuake_01">
    <Trigger Test="PerClimateRegion" BaseChance="0.003" MinTurnToOccur="40">
      <!-- Modifiers to occurance chance -->
      <ClimateModifier ID="Central Asia" Modifier="0" />
      <ClimateModifier ID="Gobi Desert" Modifier="1" />
      <ClimateModifier ID="Northern China" Modifier="0.5" />
      <ClimateModifier ID="Southern China" Modifier="1.5" />
      <ClimateModifier ID="Western China" Modifier="2" />
    </Trigger>
    <Target Affects="SettlementAndSettlementsNearby" Range="20">
      <!-- Modifiers to effects -->
      <AIDifficultyModifier VH="0.5" H="0.5" />
      <PlayerDifficultyModifier E="0.5" VH="1.5" />
      <Effect Effect="DamageBuildings" Chance="0.4">
        <TechModifier Item="Ceramic Roof Tiles" Modifier="0.33" />
      </Effect>
      <Effect Effect="DamageWalls" Chance="0.2">
        <TechModifier Item="Brick Faced Walls" Modifier="0.5" />
      </Effect>
      <Effect Effect="KillPopulation" MinPercent="10" MaxPercent="25">
        <TechModifier Item="Ceramic Roof Tiles" Modifier="0.33" />
      </Effect>
      <Effect Effect="KillCharacter" Chance="0.1" />
      <Effect Effect="KillSoldiers" MinPercent="0" MaxPercent="20" />
      <Effect Effect="NobleUnrest" Parameter="30" Duration="4" />
      <Effect Effect="PeasantUnrest" Parameter="20" Duration="4" />
    </Target>
    <ReportToPlayer EventName="DS Earthquake Msg" MainMsg="DS Major Earthquake Text" SecondaryMsg="DS Earthquake Text" />
    <ThirdPartyReport EventName="DS 3P Earthquake Msg" MainMsg="DS 3P Earthquake Text" />
  </Event>

  <!-- Fire-->
  <Event ID="Fire" Picture="OE_Event_Fire_01">
    <Trigger Test="PerSettlement" BaseChance="0.005" MinTurnToOccur="20">
      <!-- Modifiers to occurance chance -->
      <AIDifficultyModifier VH="0.5" H="0.5" />
      <PlayerDifficultyModifier E="0.5" VH="1.25" />
      <ClimateModifier ID="Southern China" Modifier="0.5" />
      <PopulationModifier LessThan="10" Modifier="0.3" />
    </Trigger>
    <Target Affects="TriggerTarget">
      <!-- Modifiers to effects -->
      <TechModifier Item="Ceramic Roof Tiles" Modifier="0.33" />
      <Effect Effect="DamageBuildings" Chance="0.4" />
      <Effect Effect="DamageWalls" Chance="0.4" Parameter="1" /> <!-- Param is max level to damage -->
      <Effect Effect="KillPopulation" MinPercent="10" MaxPercent="25" />
      <Effect Effect="KillCharacter" Chance="0.06" />
    </Target>
    <ReportToPlayer EventName="DS Fire Msg" MainMsg="DS Fire Text" />
    <ThirdPartyReport EventName="DS 3P Fire Msg" MainMsg="DS 3P Fire Text" />
  </Event>

  <!-- Flood -->
  <Event ID="Flood" Picture="OE_Event_Flood_01">
    <Trigger Test="PerClimateRegion" BaseChance="0.03" MinTurnToOccur="5">
      <!-- Modifiers to occurance chance -->
      <AIDifficultyModifier VH="0.5" H="0.5" />
      <PlayerDifficultyModifier E="0.5" VH="1.25" />
      <ClimateModifier ID="Gobi Desert" Modifier="0.5" />
      <ClimateModifier ID="Northern China" Modifier="2" />
    </Trigger>
    <Target Affects="RiverSection" Range="15">
      <!-- Modifiers to effects -->
      <AIDifficultyModifier VH="0.5" H="0.5" N="0.5" />
      <TechModifier Item="Flood Control" Modifier="0.5" />
      <Effect Effect="DamageBuildings" Chance="0.4" />
      <Effect Effect="DamageWalls" Chance="0.6">
        <TechModifier Item="Brick Faced Walls" Modifier="0" />
      </Effect>
      <Effect Effect="KillPopulation" MinPercent="20" MaxPercent="40" />
      <Effect Effect="PeasantUnrest" Parameter="20" Duration="4" />
    </Target>
    <ReportToPlayer EventName="DS Flood Msg" MainMsg="DS Flood Text" />
    <ThirdPartyReport EventName="DS 3P Flood Msg" MainMsg="DS 3P Flood Text" />
  </Event>

  <!-- Disease -->
  <Event ID="Disease" Picture="OE_Event_Sickness_01">
