=== JMonkeyFan/Oriental-Empires-Reimagined/XML/MapGeneration.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="OrientalEmpires" xmlns:oe="OrientalEmpires" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="ClimateSet">
    <xs:sequence>
      <xs:element name="ClimateGenerator" maxOccurs ="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Placement">
              <xs:complexType>
                <xs:attribute name ="Left" type="xs:float" use="required"/>
                <xs:attribute name ="Right" type="xs:float" use="required"/>
                <xs:attribute name ="Top" type="xs:float" use="required"/>
                <xs:attribute name ="Bottom" type="xs:float" use="required"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="ID" type="xs:string" use="required"/>
          <xs:attribute name="MinSeeds" type="xs:int" use="required"/>
          <xs:attribute name="MaxSeeds" type="xs:int" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:string" use="required"/>
    <xs:attribute name="Picture" type="xs:string" use="required"/>
    <xs:attribute name="MinMapArea" type="xs:int" use="optional"/>
  </xs:complexType>

  <xs:complexType name="ClimateGenerator">
    <xs:sequence>
      <xs:element name="SubClimate" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Feature" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="Weight" type="xs:int" use="required"/>
                <xs:attribute name="ID" type="xs:string" use ="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="Border">
              <xs:complexType>
                <xs:attribute name="Feature" type="xs:string" use="required"/>
                <xs:attribute name="Chance" type="xs:float" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="Headlands">
              <xs:complexType>
                <xs:attribute name="Terrain" type="xs:string" use="required"/>
                <xs:attribute name="BackTerrain" type="xs:string" use="required"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="ID" type="xs:string" use ="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:string" use="required"/>
    <xs:attribute name="ClimateType" type="xs:string" use="required"/>
    <xs:attribute name="DefaultTerrain" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="MapType">
    <xs:attribute name="ID" type="xs:string" use="required"/>
    <xs:attribute name="TemplateBaseName" type="xs:string" use="required"/>
    <xs:attribute name="PictureName" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="MapFeature">
    <xs:sequence>
      <xs:element name="Blob">
        <xs:complexType>
          <xs:attribute name="Terrain" type="xs:string" use="required"/>
          <xs:attribute name="MinLength" type="xs:int" use="required"/>
          <xs:attribute name="MaxLength" type="xs:int" use="required"/>
          <xs:attribute name="MinWidth" type="xs:float" use="required"/>
          <xs:attribute name="MaxWidth" type="xs:float" use="required"/>
          <xs:attribute name="Fill" type="xs:boolean" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Surround" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="Terrain" type="xs:string" use="required"/>
          <xs:attribute name="MinWidth" type="xs:float" use="required"/>
          <xs:attribute name="MaxWidth" type="xs:float" use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Scatter" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="Terrain" type="xs:string" use="required"/>
          <xs:attribute name="MinCoverage" type="xs:float" use="required"/>
          <xs:attribute name="MaxCoverage" type="xs:float" use="required"/>
          <xs:attribute name="All" type="xs:boolean" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:string" use="required"/>
  </xs:complexType>
  
  <xs:element name="Root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapType" type="oe:MapType" maxOccurs ="unbounded"/>
        <xs:element name="ClimateSet" type="oe:ClimateSet" maxOccurs ="unbounded"/>
        <xs:element name="TerrainFeature" type="oe:MapFeature" maxOccurs ="unbounded"/>
        <xs:element name="ClimateGenerator" type="oe:ClimateGenerator" maxOccurs ="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JMonkeyFan/Oriental-Empires-Reimagined/XML/MapGeneration.xml
<?xml version="1.0" encoding="utf-8"?>
<Root xmlns="OrientalEmpires" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="OrientalEmpires MapGeneration.xsd">
  <!-- Map Types //////////////////////////////////////////////////////-->
  <MapType ID="Island Continent" TemplateBaseName="Continent" PictureName="G_Sprite_MapContinent_01" />
  <MapType ID="Continental Edge" TemplateBaseName="EdgeContinent" PictureName="G_Sprite_MapContinentalCoast_01" />
  <MapType ID="Inland Sea" TemplateBaseName="InlandSea" PictureName="G_Sprite_MapInslandSea_01" />
  <MapType ID="Americas" TemplateBaseName="Americas" PictureName="G_Sprite_MapAmericas_01" />
  <ClimateSet ID="China And Mongolia" Picture="OE_FE_Map_ChinaMongolia_01" MinMapArea="4500">
    <ClimateGenerator ID="Central Asia" MinSeeds="3" MaxSeeds="8">
      <Placement Left="0" Right="1" Bottom="0.6" Top="1" />
    </ClimateGenerator>
    <ClimateGenerator ID="Gobi Desert" MinSeeds="2" MaxSeeds="6">
      <Placement Left="0" Right="1" Bottom="0.3" Top="0.9" />
    </ClimateGenerator>
    <ClimateGenerator ID="Northern China" MinSeeds="3" MaxSeeds="10">
      <Placement Left="0.2" Right="1" Bottom="0.3" Top="0.7" />
    </ClimateGenerator>
    <ClimateGenerator ID="Southern China" MinSeeds="3" MaxSeeds="10">
      <Placement Left="0.2" Right="1" Bottom="0" Top="0.3" />
    </ClimateGenerator>
    <ClimateGenerator ID="Western China" MinSeeds="3" MaxSeeds="10">
      <Placement Left="0" Right="0.2" Bottom="0" Top="0.6" />
    </ClimateGenerator>
  </ClimateSet>
  <ClimateSet ID="China Only" MinMapArea="2000" Picture="OE_FE_Map_ChinaAll_01">
    <ClimateGenerator ID="Northern China" MinSeeds="2" MaxSeeds="5">
      <Placement Left="0.2" Right="1" Bottom="0.6" Top="1" />
    </ClimateGenerator>
    <ClimateGenerator ID="Southern China" MinSeeds="2" MaxSeeds="5">
      <Placement Left="0.2" Right="1" Bottom="0" Top="0.4" />
    </ClimateGenerator>
    <ClimateGenerator ID="Western China" MinSeeds="2" MaxSeeds="5">
      <Placement Left="0" Right="0.2" Bottom="0" Top="0.6" />
    </ClimateGenerator>
  </ClimateSet>
  <ClimateSet ID="Northern China" Picture="OE_FE_Map_ChinaNorthern_01">
    <ClimateGenerator ID="Northern China" MinSeeds="2" MaxSeeds="10">
      <Placement Left="0" Right="1" Bottom="0" Top="1" />
    </ClimateGenerator>
  </ClimateSet>
  <ClimateSet ID="Southern China" Picture="OE_FE_Map_ChinaSouthern_01">
    <ClimateGenerator ID="Southern China" MinSeeds="2" MaxSeeds="10">
      <Placement Left="0" Right="1" Bottom="0" Top="1" />
    </ClimateGenerator>
  </ClimateSet>
  <ClimateSet ID="Western China" Picture="OE_FE_Map_ChinaWestern_01">
    <ClimateGenerator ID="Western China" MinSeeds="2" MaxSeeds="10">
      <Placement Left="0" Right="1" Bottom="0" Top="1" />
    </ClimateGenerator>
  </ClimateSet>
  <ClimateSet ID="Mongolia" Picture="OE_FE_Map_Mongolia_01">
    <ClimateGenerator ID="Central Asia" MinSeeds="4" MaxSeeds="6">
      <Placement Left="0" Right="1" Bottom="0.6" Top="1" />
    </ClimateGenerator>
    <ClimateGenerator ID="Gobi Desert" MinSeeds="2" MaxSeeds="6">
      <Placement Left="0" Right="1" Bottom="0" Top="0.3" />
    </ClimateGenerator>
  </ClimateSet> <!-- Terrain Features ////////////////////////////////////////////////////////--> <!-- Cell filling features -->
  <TerrainFeature ID="Featureless Dry Plain">
    <Blob Terrain="Dry Plain" Fill="true" MinLength="0" MaxLength="3" MinWidth="0" MaxWidth="1.75" />
    <Scatter Terrain="Grassland" MinCoverage="0" MaxCoverage="0.4" All="false" />
    <Scatter Terrain="Forest" MinCoverage="0" MaxCoverage="0.0025" All="false" />
  </TerrainFeature>
  <TerrainFeature ID="Featureless Grassy Plain">
    <Blob Terrain="Fertile Plain" Fill="true" MinLength="0" MaxLength="2" MinWidth="0" MaxWidth="1.5" />
    <Scatter Terrain="Grassland" MinCoverage="0" MaxCoverage="0.6" All="false" />
    <Scatter Terrain="Forest" MinCoverage="0" MaxCoverage="0.0025" All="false" />
  </TerrainFeature>
  <TerrainFeature ID="Wooded Grassy Plain">
    <Blob Terrain="Grassland" Fill="true" MinLength="1" MaxLength="2" MinWidth="1" MaxWidth="2.75" />
    <Scatter Terrain="Forest" MinCoverage="0.05" MaxCoverage="0.0125" All="false" />
    <Scatter Terrain="Fertile Plain" MinCoverage="0" MaxCoverage="0.25" All="false" />
    <Scatter Terrain="Gentle Hills" MinCoverage="0" MaxCoverage="0.005" All="false" />
    <Scatter Terrain="Steep Hills" MinCoverage="0" MaxCoverage="0.0125" All="false" />
    <Scatter Terrain="Mountains" MinCoverage="0" MaxCoverage="0.0075" All="false" />
  </TerrainFeature>
  <TerrainFeature ID="Wooded Fertile Plain">
    <Blob Terrain="Fertile Plain" Fill="true" MinLength="1" MaxLength="2" MinWidth="1" MaxWidth="2.75" />
    <Scatter Terrain="Forest" MinCoverage="0.05" MaxCoverage="0.01" All="false" />
    <Scatter Terrain="Grassland" MinCoverage="0" MaxCoverage="0.25" All="false" />
    <Scatter Terrain="Gentle Hills" MinCoverage="0" MaxCoverage="0.01" All="false" />
    <Scatter Terrain="Steep Hills" MinCoverage="0" MaxCoverage="0.008" All="false" />
    <Scatter Terrain="Mountains" MinCoverage="0" MaxCoverage="0.006" All="false" />
  </TerrainFeature>
  <TerrainFeature ID="Wooded Barren Plain">
    <Blob Terrain="Dry Plain" Fill="true" MinLength="1" MaxLength="2" MinWidth="1" MaxWidth="2.75" />
    <Scatter Terrain="Forest" MinCoverage="0.05" MaxCoverage="0.003" All="false" />
    <Scatter Terrain="Sand" MinCoverage="0" MaxCoverage="0.2" All="false" />
    <Scatter Terrain="Grassland" MinCoverage="0" MaxCoverage="0.2" All="false" />
    <Scatter Terrain="Fertile Plain" MinCoverage="0" MaxCoverage="0.08" All="false" />
    <Scatter Terrain="Gentle Hills" MinCoverage="0" MaxCoverage="0.008" All="false" />
    <Scatter Terrain="Steep Hills" MinCoverage="0" MaxCoverage="0.006" All="false" />
    <Scatter Terrain="Mountains" MinCoverage="0" MaxCoverage="0.01" All="false" />
  </TerrainFeature>
  <TerrainFeature ID="Wooded Fertile Plain">
    <Blob Terrain="Forest" Fill="true" MinLength="1" MaxLength="2" MinWidth="1" MaxWidth="2.75" />
    <Scatter Terrain="Forest" MinCoverage="0.05" MaxCoverage="0.45" All="false" />
    <Scatter Terrain="Fertile Plain" MinCoverage="0.25" MaxCoverage="0.8" All="false" />
    <Scatter Terrain="Grassland" MinCoverage="0.01" MaxCoverage="0.3" All="false" />
    <Scatter Terrain="Gentle Hills" MinCoverage="0" MaxCoverage="0.008" All="false" />
    <Scatter Terrain="Steep Hills" MinCoverage="0" MaxCoverage="0.008" All="false" />
    <Scatter Terrain="Mountains" MinCoverage="0" MaxCoverage="0.008" All="false" />
  </TerrainFeature>
  <TerrainFeature ID="Marshy Plain">
    <Blob Terrain="Grassland" Fill="true" MinLength="1" MaxLength="2" MinWidth="1" MaxWidth="2.75" />
    <Scatter Terrain="Forest" MinCoverage="0" MaxCoverage="0.15" All="false" />
    <Scatter Terrain="Marsh" MinCoverage="0" MaxCoverage="0.4" All="false" />
    <Scatter Terrain="Fertile Plain" MinCoverage="0" MaxCoverage="0.4" All="false" />
    <Scatter Terrain="Gentle Hills" MinCoverage="0" MaxCoverage="0.006" All="false" />
    <Scatter Terrain="Steep Hills" MinCoverage="0" MaxCoverage="0.006" All="false" />
    <Scatter Terrain="Mountains" MinCoverage="0" MaxCoverage="0.006" All="false" />
  </TerrainFeature>
  <TerrainFeature ID="Mounded Desert Plain">
    <Blob Terrain="Fertile Plain" Fill="true" MinLength="1" MaxLength="2" MinWidth="1" MaxWidth="2.75" />
    <Surround Terrain="Forest" MinWidth="0" MaxWidth="0.001" />
    <Surround Terrain="Gentle Hills" MinWidth="0" MaxWidth="0.04" />
    <Surround Terrain="Forest" MinWidth="0" MaxWidth="0.001" />
    <Surround Terrain="Plateau" MinWidth="0" MaxWidth="0.075" />
    <Surround Terrain="Forest" MinWidth="0" MaxWidth="0.001" />
    <Surround Terrain="Steep Hills" MinWidth="0" MaxWidth="0.04" />
    <Surround Terrain="Forest" MinWidth="0" MaxWidth="0.002" />
    <Surround Terrain="Plateau" MinWidth="0" MaxWidth="0.025" />
    <Surround Terrain="Forest" MinWidth="0" MaxWidth="0.001" />
    <Surround Terrain="Dry Plain" MinWidth="0" MaxWidth="0.15" />
    <Surround Terrain="Gentle Hills" MinWidth="0" MaxWidth="0.075" />
    <Surround Terrain="Dry Plain" MinWidth="0" MaxWidth="0.15" />
    <Surround Terrain="Sand" MinWidth="0" MaxWidth="0.2" />
    <Surround Terrain="Navigable River" MinWidth="0" MaxWidth="0.002" />
    <Scatter Terrain="Dry Plain" MinCoverage="0" MaxCoverage="0.01" All="false" />
  </TerrainFeature>
  <TerrainFeature ID="Mounded Fertile Plain">
    <Blob Terrain="Fertile Plain" Fill="true" MinLength="1" MaxLength="2" MinWidth="1" MaxWidth="2.75" />
    <Surround Terrain="Forest" MinWidth="0" MaxWidth="0.005" />
    <Surround Terrain="Gentle Hills" MinWidth="0" MaxWidth="0.075" />
    <Surround Terrain="Forest" MinWidth="0" MaxWidth="0.005" />
    <Surround Terrain="Plateau" MinWidth="0" MaxWidth="0.075" />
    <Surround Terrain="Forest" MinWidth="0" MaxWidth="0.005" />
    <Surround Terrain="Gentle Hills" MinWidth="0" MaxWidth="0.075" />
    <Surround Terrain="Forest" MinWidth="0" MaxWidth="0.005" />
    <Scatter Terrain="Forest" MinCoverage="0" MaxCoverage="0.01" All="false" />
  </TerrainFeature>
  <TerrainFeature ID="Mounded Grassy Plain">
    <Blob Terrain="Grassland" Fill="true" MinLength="1" MaxLength="2" MinWidth="1" MaxWidth="2.75" />
    <Surround Terrain="Gentle Hills" MinWidth="0" MaxWidth="0.075" />
    <Scatter Terrain="Plateau" MinCoverage="0" MaxCoverage="0.0075" All="false" />
    <Scatter Terrain="Fertile Plain" MinCoverage="0" MaxCoverage="0.4" All="false" />
    <Scatter Terrain="Gentle Hills" MinCoverage="0" MaxCoverage="0.0008" All="false" />
    <Scatter Terrain="Steep Hills" MinCoverage="0" MaxCoverage="0.0009" All="false" />
    <Scatter Terrain="Mountains" MinCoverage="0" MaxCoverage="0.0005" All="false" />
