=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Offices.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="OrientalEmpires" xmlns:oe="OrientalEmpires" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:include schemaLocation="Requirement.xsd"/>
  <xs:include schemaLocation="OECommon.xsd"/>

  <xs:simpleType name="EffectArea">
    <xs:restriction base="xs:string">
      <xs:enumeration value="RecoveryRate"/>
      <xs:enumeration value="PeasantUnrest"/>
      <xs:enumeration value="RecruitmentCost"/>
      <xs:enumeration value="RecruitmentRecovery"/>
      <xs:enumeration value="CivilCandidateQuality"/>
      <xs:enumeration value="NobleUnrest"/>
      <xs:enumeration value="Authority"/>
      <xs:enumeration value="IncreaseCourtCharacters"/>
      <xs:enumeration value="ReduceCorruption"/>
      <xs:enumeration value="MeleeCombat"/>
      <xs:enumeration value="InfantryCombat"/>
      <xs:enumeration value="MountedCombat"/>      
      <xs:enumeration value="IncreaseTax"/>
      <xs:enumeration value="FoodProduction"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="BudgetType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LandUpkeepCost"/>
      <xs:enumeration value="AllIncome"/>
      <xs:enumeration value="Government"/>
      <xs:enumeration value="SecularBuildingUpkeep"/>
      <xs:enumeration value="ReligiousBuildingUpkeep"/>
      <xs:enumeration value="RecruitmentCost"/>
      <xs:enumeration value="Tribute"/>
      <xs:enumeration value="Justice"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="Budget">
    <xs:attribute name="Type" type="oe:BudgetType" use="required"/>
    <xs:attribute name="ImmuneAmount" type="xs:int" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="OfficeEffect">
    <xs:attribute name="Type" type="oe:EffectArea" use="required"/>
    <xs:attribute name="Base" type="xs:float" use="required"/>
    <xs:attribute name="EffectModifier" type="xs:float" use="optional"/>
    <xs:attribute name="EffectModifier2" type="xs:float" use="optional"/>
    <xs:attribute name="CorruptionModifier" type="xs:float" use="optional"/>
    <xs:attribute name="Max" type="xs:float" use="optional"/>
    <xs:attribute name="Min" type="xs:float" use="optional"/>
  </xs:complexType>
  
  <!-- Definition for a single office -->
  <xs:complexType name ="Office">
    <xs:sequence>
      <xs:element name="Seniority">
        <xs:complexType>
          <xs:attribute name="Max" type="xs:integer" use="required"/>
          <xs:attribute name="IncreaseYears" type="xs:integer" use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Effectiveness">
        <xs:complexType>
          <xs:attribute name="Energy" type="xs:float" use="required"/>
          <xs:attribute name="Virtue" type="xs:float" use="required"/>
          <xs:attribute name="Seniority" type="xs:float" use="required"/>
          <xs:attribute name="HasHolderBonus" type="xs:float" use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Effectiveness2" minOccurs="0">
        <xs:complexType>
          <xs:attribute name="Energy" type="xs:float" use="required"/>
          <xs:attribute name="Virtue" type="xs:float" use="required"/>
          <xs:attribute name="Seniority" type="xs:float" use="required"/>
          <xs:attribute name="HasHolderBonus" type="xs:float" use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Effect" type="oe:OfficeEffect" maxOccurs="unbounded" minOccurs ="0"/>
      <xs:element name="Budget" maxOccurs="unbounded" minOccurs ="0">
        <xs:complexType>
          <xs:attribute name="Type" type="oe:BudgetType" use="required"/>
          <xs:attribute name="Modifier" type="xs:float" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name ="ID" type="xs:string" use ="required"></xs:attribute>
    <xs:attribute name ="MustBeGeneral" type="xs:boolean" use ="optional"></xs:attribute>
    <xs:attribute name ="IsAdvisor" type="xs:boolean" use ="optional"></xs:attribute>
  </xs:complexType>

  <xs:element name="Root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Budget" type="oe:Budget" maxOccurs="unbounded"/>
        <xs:element name="Office" type="oe:Office" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Offices.xml
<?xml version="1.0" encoding="utf-8"?>
<Root xmlns="OrientalEmpires" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="OrientalEmpires Offices.xsd">

  <!-- Budgets subject to corruption effects -->
  <Budget Type="AllIncome" ImmuneAmount="300" />
  <Budget Type="LandUpkeepCost" ImmuneAmount="150" />
  <Budget Type="SecularBuildingUpkeep" ImmuneAmount="200" />
  <Budget Type="ReligiousBuildingUpkeep" ImmuneAmount="100" />
  <Budget Type="RecruitmentCost" ImmuneAmount="150" />
  <Budget Type="Justice" ImmuneAmount="150" />
  <Budget Type="Government" ImmuneAmount="150" />

  <Office ID="Grand Commandant" MustBeGeneral="true">
    <Seniority Max="5" IncreaseYears="2" />
    <Effectiveness Energy="1" Virtue="0" Seniority="0.5" HasHolderBonus="1.5" />
    <Effect Type="InfantryCombat" Base="0.9" EffectModifier="0.5" />
    <Effect Type="NobleUnrest" Base="-10" EffectModifier2="25" />
    <Effect Type="Authority" Base="0" EffectModifier="3" />
    <Budget Type="LandUpkeepCost" />
  </Office>

  <Office ID="Grand Chancellor" MustBeGeneral="false">
    <Seniority Max="5" IncreaseYears="2" />
    <Effectiveness Energy="1" Virtue="-0.5" Seniority="0.5" HasHolderBonus="2.5" />
    <Effectiveness2 Energy="1" Virtue="-0.5" Seniority="-0.5" HasHolderBonus="0" />
    <Effect Type="IncreaseTax" Base="0.9" EffectModifier="0.4" />
    <Effect Type="NobleUnrest" Base="-10" EffectModifier2="25" />
    <Effect Type="Authority" Base="0" EffectModifier="3" />
    <Budget Type="AllIncome" />
  </Office>

  <Office ID="Imperial Counsellor" MustBeGeneral="false">
    <Seniority Max="5" IncreaseYears="2" />
    <Effectiveness Energy="1" Virtue="1" Seniority="0.5" HasHolderBonus="2.5" />
    <Effect Type="FoodProduction" Base="0.9" EffectModifier="0.33" />
    <Effect Type="PeasantUnrest" Base="-15" EffectModifier2="16" />
    <Effect Type="Authority" Base="0" EffectModifier="3" />
    <Budget Type="SecularBuildingUpkeep" />
  </Office>

  <Office ID="Minister Coachman" MustBeGeneral="true">
    <Seniority Max="3" IncreaseYears="2" />
    <Effectiveness Energy="0.5" Virtue="1" Seniority="0.5" HasHolderBonus="5" />
    <Effectiveness2 Energy="1" Virtue="0" Seniority="0.5" HasHolderBonus="1.5" />
    <Effect Type="MountedCombat" Base="0.9" EffectModifier2="0.5" />
    <Effect Type="PeasantUnrest" Base="-15" EffectModifier2="16" />
    <Effect Type="Authority" Base="0" EffectModifier="3" />
    <Budget Type="RecruitmentCost" />
  </Office>

  <Office ID="Minister of Rites" MustBeGeneral="false">
    <Seniority Max="3" IncreaseYears="2" />
    <Effectiveness Energy="0" Virtue="-1" Seniority="-0.5" HasHolderBonus="0" />
    <!--    <Effect Type="CivilCandidateQuality" Base="0.5" EffectModifier="1"/> -->
    <Effect Type="NobleUnrest" Base="-10" EffectModifier2="16" />
    <Effect Type="IncreaseTax" Base="0.9" EffectModifier="0.4" />
    <Effect Type="Authority" Base="0" EffectModifier="3" />
    <Budget Type="ReligiousBuildingUpkeep" />
  </Office>

  <Office ID="Minister of Justice" MustBeGeneral="false">
    <Seniority Max="3" IncreaseYears="2" />
    <Effectiveness Energy="-1" Virtue="-1" Seniority="-0.5" HasHolderBonus="-2.5" />
    <Effect Type="NobleUnrest" Base="-15" EffectModifier2="12" />
    <Effect Type="PeasantUnrest" Base="-15" EffectModifier2="12" />
    <Effect Type="Authority" Base="0" EffectModifier="3" />
    <Budget Type="Justice" />
  </Office>

  <Office ID="Advisor 1" MustBeGeneral="false" IsAdvisor="true">
    <Seniority Max="5" IncreaseYears="2" />
    <Effectiveness Energy="0" Virtue="0" Seniority="1" HasHolderBonus="5" />
    <Effectiveness2 Energy="0" Virtue="1" Seniority="0.5" HasHolderBonus="1" />
    <Effect Type="Authority" Base="0" EffectModifier="6" />
    <Effect Type="ReduceCorruption" Base="0" EffectModifier2="0.5" />
    <Effect Type="IncreaseCourtCharacters" Base="0" EffectModifier="1.75" />
  </Office>

  <Office ID="Advisor 2" MustBeGeneral="false" IsAdvisor="true">
    <Seniority Max="5" IncreaseYears="2" />
    <Effectiveness Energy="0" Virtue="0" Seniority="1" HasHolderBonus="5" />
    <Effectiveness2 Energy="0" Virtue="1" Seniority="0.5" HasHolderBonus="2.5" />
    <Effect Type="Authority" Base="0" EffectModifier="6" />
    <Effect Type="ReduceCorruption" Base="0" EffectModifier2="1" />
    <Effect Type="IncreaseCourtCharacters" Base="0" EffectModifier="2" />
  </Office>

</Root>
