=== JMonkeyFan/Oriental-Empires-Reimagined/XML/ProjectileTypes.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="OrientalEmpires" xmlns:oe="OrientalEmpires" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Root Element -->
  <xs:element name ="Projectiles">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Projectile" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Firing">
                <xs:complexType>
                  <xs:attribute name="MaxRange" type="xs:float" use="required"/>
                  <xs:attribute name="MinRange" type="xs:float" use="optional"/>
                  <xs:attribute name="HalfFiringArcDegrees" type="xs:float" use="required"/>
                  <xs:attribute name="AccuraryAngleDegrees" type="xs:float" use="required"/>
                  <xs:attribute name="AccuracyRangePercent" type="xs:float" use="required"/>
                  <xs:attribute name="LaunchAngleDegrees" type="xs:float" use="optional"/>
                </xs:complexType>
              </xs:element>
              <!-- This is used for projectiles that have a fixed firing velocity, and whose range is determined by varying the angle of elevation-->
              <xs:element name="FiringVelocity" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="Velocity" type="xs:float" use="required"/>
                  <xs:attribute name="MinFiringAngle" type="xs:float" use="required"/>
                  <xs:attribute name="MaxFiringAngle" type="xs:float" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="FiringSequence">
                <xs:complexType>
                  <xs:attribute name="Name" type="xs:string" use="required"/>
                  <xs:attribute name="ReloadLoops" type="xs:int" use="optional"/>
                  <xs:attribute name="Shots" type="xs:int" use="optional"/>
                  <xs:attribute name="FiringDelay" type="xs:float" use="optional"/>
                  <xs:attribute name="FireEffectPrefab" type="xs:string" use="optional"/>
                  <xs:attribute name="FiringSound" type="xs:string" use="optional"/>
                  <xs:attribute name="MissileSound" type="xs:string" use="optional"/>
                  <xs:attribute name="ReloadSound" type="xs:string" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Damage">
                <xs:complexType>
                  <xs:attribute name="HitEffectPrefab" type="xs:string" use="optional"/>
                  <xs:attribute name="Damage" type="xs:int" use="required"/>
                  <xs:attribute name="APLevel" type="xs:int" use="optional"/>
                  <xs:attribute name="TerrorFactor" type="xs:int" use="optional"/>
                  <xs:attribute name="PoorVsArmor" type="xs:boolean" use="optional"/>
                  <xs:attribute name="SoldierPiercing" type="xs:boolean" use="optional"/>
                  <xs:attribute name="IgnoreSoldiersForCollision" type="xs:boolean" use="optional"/>
                  <xs:attribute name="Sound" type="xs:string" use="optional"/>
                  <xs:attribute name="KillBonusCapability" type="xs:string" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="BuildingDamage" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="HitEffectPrefab" type="xs:string" use="required"/>
                  <xs:attribute name="Damage" type="xs:int" use="required"/>
                  <xs:attribute name="FireDamage" type="xs:int" use="optional"/>
                  <xs:attribute name="Sound" type="xs:string" use="required"/>
                  <xs:attribute name="MaxHPCanDamage" type="xs:int" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Explosion" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name='EffectPrefab' type='xs:string' use='required'/>
                  <xs:attribute name="Damage" type="xs:int" use="required"/>
                  <xs:attribute name="Radius" type="xs:float" use="required"/>
                  <xs:attribute name="Sound" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ID" type="xs:string" use="required"/>
            <xs:attribute name="Prefab" type="xs:string" use="required"/>
            <xs:attribute name="RequiredTech" type="xs:string" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JMonkeyFan/Oriental-Empires-Reimagined/XML/ProjectileTypes.xml
<?xml version="1.0" encoding="utf-8"?>
<Projectiles xmlns="OrientalEmpires" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="OrientalEmpires ProjectileTypes.xsd">

  <!-- Trebuchet Projectiles -->
  <Projectile ID="STrebRock" Prefab="OE_P_Projectile_Rock_Large">
    <Firing MinRange="10" MaxRange="150" HalfFiringArcDegrees="22.5" AccuracyRangePercent="10" AccuraryAngleDegrees="5" LaunchAngleDegrees="30" />
    <FiringSequence Name="StandardArtillery" FiringSound="Small Trebuchet Fire" MissileSound="Rock In Flight" />
    <Damage Damage="10" />
    <BuildingDamage Damage="12" MaxHPCanDamage="200" HitEffectPrefab="OE_P_ImpactWall_Large" Sound="SmallRockHitsWall" />
    <Explosion EffectPrefab="OE_P_ImpactWall_Large" Damage="4" Radius="1.5" Sound="SmallRockHit" />
  </Projectile>
  <Projectile ID="STrebFlamingRock" Prefab="OE_P_Projectile_RockFire_Large" RequiredTech="Flaming Pitch">
    <Firing MinRange="10" MaxRange="150" HalfFiringArcDegrees="22.5" AccuracyRangePercent="10" AccuraryAngleDegrees="5" LaunchAngleDegrees="30" />
    <FiringSequence Name="StandardArtillery" FiringSound="Small Trebuchet Fire" MissileSound="Flaming Rock In Flight" />
    <Damage Damage="12" />
    <BuildingDamage Damage="5" FireDamage="30" MaxHPCanDamage="200" HitEffectPrefab="OE_P_ImpactWallExpolosion_Large" Sound="SmallFlamingRockHitsWall" />
    <Explosion EffectPrefab="OE_P_ImpactWallExpolosion_Large" Damage="6" Radius="1.5" Sound="SmallFlamingRockHitsWall" />
  </Projectile>
  <Projectile ID="STrebBomb" Prefab="OE_P_Projectile_Smoke_Medium" RequiredTech="Thunderclap Bomb">
    <Firing MinRange="10" MaxRange="150" HalfFiringArcDegrees="22.5" AccuracyRangePercent="10" AccuraryAngleDegrees="5" LaunchAngleDegrees="30" />
    <FiringSequence Name="StandardArtillery" FiringSound="Small Trebuchet Fire" MissileSound="Rock In Flight" />
    <Damage Damage="12" APLevel="1" TerrorFactor="1" />
    <BuildingDamage Damage="0" FireDamage="0" MaxHPCanDamage="0" HitEffectPrefab="OE_P_ImpactWallThunderClap_Medium" Sound="ShellExplosionSmall" />
    <Explosion EffectPrefab="OE_P_ImpactWallThunderClap_Medium" Damage="8" Radius="2" Sound="ShellExplosionSmall" />
  </Projectile>

  <Projectile ID="MTrebRock" Prefab="OE_P_Projectile_Rock_Large">
    <Firing MinRange="20" MaxRange="150" HalfFiringArcDegrees="22.5" AccuracyRangePercent="10" AccuraryAngleDegrees="5" LaunchAngleDegrees="30" />
    <FiringSequence Name="StandardArtillery" FiringSound="Medium Trebuchet Fire" MissileSound="Rock In Flight" />
    <Damage Damage="20" APLevel="2" />
    <BuildingDamage Damage="20" MaxHPCanDamage="300" HitEffectPrefab="OE_P_ImpactWall_Large" Sound="MediumRockHitsWall" />
    <Explosion EffectPrefab="OE_P_ImpactWall_Large" Damage="5" Radius="2" Sound="MediumRockHit" />
  </Projectile>
  <Projectile ID="MTrebFlamingRock" Prefab="OE_P_Projectile_RockFire_Large" RequiredTech="Flaming Pitch">
    <Firing MinRange="20" MaxRange="150" HalfFiringArcDegrees="22.5" AccuracyRangePercent="10" AccuraryAngleDegrees="5" LaunchAngleDegrees="30" />
    <FiringSequence Name="StandardArtillery" FiringSound="Medium Trebuchet Fire" MissileSound="Flaming Rock In Flight" />
    <Damage Damage="24" APLevel="2" />
    <BuildingDamage Damage="10" FireDamage="50" MaxHPCanDamage="300" HitEffectPrefab="OE_P_ImpactWallExpolosion_Large" Sound="MediumFlamingRockHitsWall" />
    <Explosion EffectPrefab="OE_P_ImpactWallExpolosion_Large" Damage="6" Radius="2.5" Sound="MediumFlamingRockHitsWall" />
  </Projectile>
  <Projectile ID="MTrebBomb" Prefab="OE_P_Projectile_Smoke_Medium" RequiredTech="Thunderclap Bomb">
    <Firing MinRange="20" MaxRange="150" HalfFiringArcDegrees="22.5" AccuracyRangePercent="10" AccuraryAngleDegrees="5" LaunchAngleDegrees="30" />
    <FiringSequence Name="StandardArtillery" FiringSound="Medium Trebuchet Fire" MissileSound="Rock In Flight" />
    <Damage Damage="24" APLevel="1" TerrorFactor="1" />
    <BuildingDamage Damage="0" FireDamage="0" MaxHPCanDamage="0" HitEffectPrefab="OE_P_ImpactWallThunderClap_Medium" Sound="ShellExplosionMedium" />
    <Explosion EffectPrefab="OE_P_ImpactWallThunderClap_Medium" Damage="8" Radius="3" Sound="ShellExplosionMedium" />
  </Projectile>

  <Projectile ID="LTrebRock" Prefab="OE_P_Projectile_Rock_Large">
    <Firing MinRange="20" MaxRange="180" HalfFiringArcDegrees="22.5" AccuracyRangePercent="10" AccuraryAngleDegrees="3" LaunchAngleDegrees="30" />
    <FiringSequence Name="StandardArtillery" FiringSound="Large Trebuchet Fire" MissileSound="Rock In Flight" />
    <Damage Damage="40" APLevel="2" />
    <BuildingDamage Damage="30" MaxHPCanDamage="99999" HitEffectPrefab="OE_P_ImpactWall_Large" Sound="LargeRockHitsWall" />
    <Explosion EffectPrefab="OE_P_ImpactWall_Large" Damage="8" Radius="3" Sound="LargeRockHit" />
  </Projectile>
  <Projectile ID="LTrebFlamingRock" Prefab="OE_P_Projectile_RockFire_Large" RequiredTech="Flaming Pitch">
    <Firing MinRange="20" MaxRange="180" HalfFiringArcDegrees="22.5" AccuracyRangePercent="10" AccuraryAngleDegrees="5" LaunchAngleDegrees="30" />
    <FiringSequence Name="StandardArtillery" FiringSound="Large Trebuchet Fire" MissileSound="Flaming Rock In Flight" />
    <Damage Damage="50" APLevel="2" />
    <BuildingDamage Damage="15" FireDamage="70" MaxHPCanDamage="99999" HitEffectPrefab="OE_P_ImpactWallExpolosion_Large" Sound="LargeFlamingRockHitsWall" />
    <Explosion EffectPrefab="OE_P_ImpactWallExpolosion_Large" Damage="10" Radius="3.5" Sound="LargeRockHit" />
  </Projectile>
  <Projectile ID="LTrebBomb" Prefab="OE_P_Projectile_Smoke_Medium" RequiredTech="Thunderclap Bomb">
    <Firing MinRange="20" MaxRange="180" HalfFiringArcDegrees="22.5" AccuracyRangePercent="10" AccuraryAngleDegrees="5" LaunchAngleDegrees="30" />
    <FiringSequence Name="StandardArtillery" FiringSound="Large Trebuchet Fire" MissileSound="Rock In Flight" />
    <Damage Damage="50" APLevel="1" TerrorFactor="1" />
    <BuildingDamage Damage="0" FireDamage="0" MaxHPCanDamage="0" HitEffectPrefab="OE_P_ImpactWallThunderClap_Medium" Sound="ShellExplosionLarge" />
    <Explosion EffectPrefab="OE_P_ImpactWallThunderClap_Medium" Damage="12" Radius="4" Sound="ShellExplosionLarge" />
  </Projectile>

  <Projectile ID="LCWTrebRock" Prefab="OE_P_Projectile_Rock_Large">
    <Firing MinRange="20" MaxRange="180" HalfFiringArcDegrees="22.5" AccuracyRangePercent="3" AccuraryAngleDegrees="3" LaunchAngleDegrees="30" />
    <FiringSequence Name="StandardArtillery" FiringSound="Counterweight Trebuchet Fire" MissileSound="Rock In Flight" />
    <Damage Damage="40" APLevel="2" />
    <BuildingDamage Damage="60" MaxHPCanDamage="99999" HitEffectPrefab="OE_P_ImpactWall_Large" Sound="LargeRockHitsWall" />
    <Explosion EffectPrefab="OE_P_ImpactWall_Large" Damage="10" Radius="3" Sound="LargeRockHit" />
  </Projectile>
  <Projectile ID="LCWTrebFlamingRock" Prefab="OE_P_Projectile_RockFire_Large" RequiredTech="Flaming Pitch">
    <Firing MinRange="20" MaxRange="180" HalfFiringArcDegrees="22.5" AccuracyRangePercent="3" AccuraryAngleDegrees="3" LaunchAngleDegrees="30" />
    <FiringSequence Name="StandardArtillery" FiringSound="Counterweight Trebuchet Fire" MissileSound="Flaming Rock In Flight" />
    <Damage Damage="50" APLevel="2" />
    <BuildingDamage Damage="30" FireDamage="90" MaxHPCanDamage="99999" HitEffectPrefab="OE_P_ImpactWallFire_Large" Sound="LargeFlamingRockHitsWall" />
    <Explosion EffectPrefab="OE_P_ImpactWallExpolosion_Large" Damage="12" Radius="3.5" Sound="LargeRockHit" />
  </Projectile>
  <Projectile ID="LCWTrebBomb" Prefab="OE_P_Projectile_Smoke_Medium" RequiredTech="Thunderclap Bomb">
    <Firing MinRange="20" MaxRange="180" HalfFiringArcDegrees="22.5" AccuracyRangePercent="3" AccuraryAngleDegrees="3" LaunchAngleDegrees="30" />
    <FiringSequence Name="StandardArtillery" FiringSound="Counterweight Trebuchet Fire" MissileSound="Rock In Flight" />
    <Damage Damage="50" APLevel="1" TerrorFactor="1" />
    <BuildingDamage Damage="0" FireDamage="0" MaxHPCanDamage="0" HitEffectPrefab="OE_P_ImpactWallThunderClap_Medium" Sound="ShellExplosionLarge" />
    <Explosion EffectPrefab="OE_P_ImpactWallThunderClap_Medium" Damage="14" Radius="4" Sound="ShellExplosionLarge" />
  </Projectile>

  <!-- Ballista Projectiles -->
  <Projectile ID="SBallistaBolt" Prefab="OE_P_Projectile_BalistaBoltSmall">
    <Firing MinRange="5" MaxRange="150" HalfFiringArcDegrees="22.5" AccuracyRangePercent="2" AccuraryAngleDegrees="2" LaunchAngleDegrees="15" />
    <FiringSequence Name="StandardArtillery" FiringSound="Large Crossbow Fire" ReloadSound="Large Crossbow Reload" />
    <Damage Damage="15" APLevel="2" SoldierPiercing="true" />
    <BuildingDamage Damage="7" MaxHPCanDamage="100" HitEffectPrefab="OE_P_ImpactWall_Small" Sound="BallistaBoltHitsWall" />
  </Projectile>
  <Projectile ID="LBallistaBolt" Prefab="OE_P_Projectile_BalistaBoltLarge">
    <Firing MinRange="20" MaxRange="250" HalfFiringArcDegrees="22.5" AccuracyRangePercent="3" AccuraryAngleDegrees="3" LaunchAngleDegrees="15" />
    <FiringSequence Name="StandardArtillery" FiringSound="Large Crossbow Fire" ReloadSound="Large Crossbow Reload" />
    <Damage Damage="25" APLevel="2" SoldierPiercing="true" />
    <BuildingDamage Damage="12" MaxHPCanDamage="100" HitEffectPrefab="OE_P_ImpactWall_Small" Sound="BallistaBoltHitsWall" />
  </Projectile>

  <!-- Cannons and rockets -->
  <Projectile ID="SCannonBall" Prefab="OE_P_Projectile_CannonBall_Large">
    <Firing MinRange="0" MaxRange="250" HalfFiringArcDegrees="12" AccuracyRangePercent="2" AccuraryAngleDegrees="2" LaunchAngleDegrees="5" />
    <FiringSequence Name="SCannon" FireEffectPrefab="OE_P_MuzzleFlash_Large" FiringSound="Small Cannon Fire" />
    <Damage Damage="50" APLevel="2" SoldierPiercing="true" />
