=== JMonkeyFan/Oriental-Empires-Reimagined/XML/ResourcesAndTrade.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="OrientalEmpires" xmlns:oe="OrientalEmpires" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Enumeration of ambient creature actions -->
  <xs:simpleType name="ResourceUse">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Food"/>
      <xs:enumeration value="Trade"/>
      <xs:enumeration value="Money"/>
      <xs:enumeration value="ProductionBoost"/>
      <xs:enumeration value="Network"/>
      <xs:enumeration value="Other"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="MapResource">
    <xs:sequence minOccurs="0">
      <xs:element name="DotColor" minOccurs ="0">
        <xs:complexType>
          <xs:attribute name="R" type="xs:nonNegativeInteger" use ="required"/>
          <xs:attribute name="G" type="xs:nonNegativeInteger" use ="required"/>
          <xs:attribute name="B" type="xs:nonNegativeInteger" use ="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Placement" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="Terrain" type="xs:string" use ="required"/>
          <xs:attribute name="Climate" type="xs:string" use ="optional"/>
          <xs:attribute name="Chance" type="xs:float" use ="required"/>
          <xs:attribute name="PlacementSet" type="xs:string" use ="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:string" use ="required"/>
    <xs:attribute name="IconName" type="xs:string" use ="required"/>
    <xs:attribute name="HighlightIcon" type="xs:string" use ="required"/>
    <xs:attribute name="Use" type="oe:ResourceUse" use ="required"/>
    <xs:attribute name="Value" type="xs:nonNegativeInteger" use ="optional"/>
    <xs:attribute name="AmbientItemSet" type="xs:string" use ="optional"/>
    <xs:attribute name="TradeItem" type="xs:string" use ="optional"/>
    <xs:attribute name="BoostTradeItem" type="xs:string" use ="optional"/>
  </xs:complexType>
  
  <xs:element name="Root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapResource" type="oe:MapResource" maxOccurs ="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JMonkeyFan/Oriental-Empires-Reimagined/XML/ResourcesAndTrade.xml
<?xml version="1.0" encoding="utf-8"?>
<Root xmlns="OrientalEmpires" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="OrientalEmpires ResourcesAndTrade.xsd">
  <!--
  <MapResource ID="Rhinoceros" IconName="G_Icon_Resource_Rhino_01" HighlightIcon="G_Icon_Resource_Rhino_01_Active" Use="Money" Value="60" AmbientItemSet="Rhino Herd">
    <Placement Terrain="Fertile Plain" Climate="Northern China" Chance="0.01"/>
    <Placement Terrain="Fertile Plain" Climate="Southern China" Chance="0.01"/>
    <Placement Terrain="Fertile Plain" Climate="Western China" Chance="0.01"/>
  </MapResource>

  <MapResource ID="Wild Horses" IconName="G_Icon_Resource_Horse_01" HighlightIcon="G_Icon_Resource_Horse_01_Active"  Use="Trade" TradeItem ="Horses" AmbientItemSet="Wild Horse Herd">
    <Placement Terrain="Grassland" Climate="Northern China" Chance="0.01"/>
    <Placement Terrain="Grassland" Climate="Western China" Chance="0.01"/>
    <Placement Terrain="Grassland" Climate="Central Asia" Chance="0.01"/>
    <Placement Terrain="Fertile Plain" Climate="Central Asia" Chance="0.01"/>
  </MapResource>

  <MapResource ID="Wild Game" IconName="G_Icon_Resource_WildGame_01" HighlightIcon="G_Icon_Resource_WildGame_01_Active"  Use="Food" Value="3" AmbientItemSet="Deer Herd">
    <Placement Terrain="Fertile Plain" Chance="0.01"/>
    <Placement Terrain="Grassland" Chance="0.005"/>
  </MapResource>

  <MapResource ID="Fish" IconName="G_Icon_Resource_Fish_01" HighlightIcon="G_Icon_Resource_Fish_01_Active"  Use="Food" Value="4" AmbientItemSet="Fish Shoal">
    <Placement Terrain="Navigable River" Chance="0.04"/>
    <Placement Terrain="Coastal" Chance="0.04"/>
  </MapResource>

  <MapResource ID="Copper" IconName="G_Icon_Resource_Copper_01" HighlightIcon="G_Icon_Resource_Copper_01_Active"  Use="ProductionBoost" BoostTradeItem="Bronze" Value="30">
    <DotColor R="255" G="0" B="255"/>
    <Placement Terrain="Mountains" Chance="0.065"/>
    <Placement Terrain="Steep Hills" Chance="0.065"/>
  </MapResource>

  <MapResource ID="Gold" IconName="G_Icon_Resource_Gold_01" HighlightIcon="G_Icon_Resource_Gold_01_Active"  Use="Other">
    <DotColor R="255" G="0" B="255"/>
    <Placement Terrain="Mountains" Chance="0.25"/>
  </MapResource>

  <MapResource ID="Jade" IconName="G_Icon_Resource_Jade_01" HighlightIcon="G_Icon_Resource_Jade_01_Active"  Use="Other">
    <DotColor R="255" G="0" B="255"/>
    <Placement Terrain="Mountains" Chance="0.15"/>
  </MapResource>

 <MapResource ID="Kaolinite" IconName="G_Icon_Resource_WhiteClay_01" HighlightIcon="G_Icon_Resource_WhiteClay_01_Active"  Use="ProductionBoost" BoostTradeItem="Ceramics" Value="30">
    <Placement Terrain="Gentle Hills" Chance="0.002"/>
  </MapResource>

  <MapResource ID="Mulberry" IconName="G_Icon_Resource_Mulberry_01" HighlightIcon="G_Icon_Resource_Mulberry_01_Active"  Use="ProductionBoost" BoostTradeItem="Silk" Value="30">
    <Placement Terrain="Fertile Plain" Climate="Northern China" Chance="0.003"/>
    <Placement Terrain="Fertile Plain" Climate="Southern China" Chance="0.003"/>
    <Placement Terrain="Fertile Plain" Climate="Western China" Chance="0.003"/>
  </MapResource>

  <MapResource ID="Bamboo" IconName="G_Icon_Resource_Bamboo_01" HighlightIcon="G_Icon_Resource_Bamboo_01_Active" Use="Trade" TradeItem ="Bamboo">
    <Placement Terrain="Fertile Plain" Climate="Southern China" Chance="0.001"/>
    <Placement Terrain="Forest" Climate="Southern China" Chance="0.003"/>
    <Placement Terrain="Forest" Climate="Western China" Chance="0.003"/>
  </MapResource>

  <MapResource ID="ZhennanWood" IconName="G_Icon_Resource_ZhennanWood_01" HighlightIcon="G_Icon_Resource_ZhennanWood_01_Active" Use="Trade" TradeItem ="Zhennan Wood">
    <Placement Terrain="Forest" Climate="Western China" Chance="0.002"/>
  </MapResource>

  <MapResource ID="Sable" IconName="G_Icon_Resource_Sable_02" HighlightIcon="G_Icon_Resource_Sable_02_Active" Use="Trade" TradeItem ="Sable Fur">
    <Placement Terrain="Forest" Climate="Central Asia" Chance="0.003"/>
  </MapResource>

  <MapResource ID="Falcons" IconName="G_Icon_Resource_Falcons_01" HighlightIcon="G_Icon_Resource_Falcons_01_Active" Use="Trade" TradeItem ="Falcons">
    <Placement Terrain="Steep Hills" Climate="Central Asia" Chance="0.007"/>
  </MapResource>

  <MapResource ID="Goats" IconName="G_Icon_Resource_WildGoats_01" HighlightIcon="G_Icon_Resource_WildGoats_01_Active" Use="Food" Value ="2">
    <Placement Terrain="Steep Hills" Climate="Central Asia" Chance="0.002"/>
    <Placement Terrain="Steep Hills" Climate="Gobi Desert" Chance="0.003"/>
    <Placement Terrain="Steep Hills" Climate="Central Asia DLC" Chance="0.003"/>
    <Placement Terrain="Steep Hills" Climate="Western China" Chance="0.002"/>
  </MapResource>-->

  <!-- Trade Networks -->
  <MapResource ID="Silk Road West" IconName="G_Icon_Resource_TradeRoute_Carpet_01" HighlightIcon="G_Icon_Resource_TradeRoute_Carpet_01_Active" Use="Network" Value="100" />
  <MapResource ID="Silk Road East" IconName="G_Icon_Resource_TradeRoute_Silk_01" HighlightIcon="G_Icon_Resource_TradeRoute_Silk_01_Active" Use="Network" Value="100" />
  <MapResource ID="Silk Road Central" IconName="G_Icon_Resource_TradeRoute_Jade_01" HighlightIcon="G_Icon_Resource_TradeRoute_Jade_01_Active" Use="Network" Value="100" />
  <MapResource ID="Spice Road" IconName="G_Icon_Resource_TradeRoute_Spice_01" HighlightIcon="G_Icon_Resource_TradeRoute_Spice_01_Active" Use="Network" Value="100" />
  <MapResource ID="Falcon Road" IconName="G_Icon_Resource_TradeRoute_Falcon_01" HighlightIcon="G_Icon_Resource_TradeRoute_Falcon_01_Active" Use="Network" Value="100" />
  <MapResource ID="Sable Road" IconName="G_Icon_Resource_TradeRoute_Fur_02" HighlightIcon="G_Icon_Resource_TradeRoute_Fur_02_Active" Use="Network" Value="100" />

  <MapResource ID="Trade Route2" IconName="G_Icon_Resource_TradeRoute_01" HighlightIcon="G_Icon_Resource_TradeRoute_01_Active" Use="Money" Value="100"></MapResource>
  <!--
  <MapResource ID="Sea Trade Route2" IconName="G_Icon_Resource_SeaTradeRoute_01" HighlightIcon="G_Icon_Resource_SeaTradeRoute_01_Active"  Use="Money" Value="150">
  </MapResource>
-->

</Root>

=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Mod ResourcesAndTrade.xml
<?xml version="1.0" encoding="utf-8"?>
<Root xmlns="OrientalEmpires" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="OrientalEmpires ResourcesAndTrade.xsd">
  <!--Resources-->
  <MapResource ID="Copper" IconName="Resources\CopperBoost" HighlightIcon="Resources\CopperBoost" Use="ProductionBoost" BoostTradeItem="Copper" Value="160">
    <DotColor R="255" G="0" B="255" />
    <Placement Terrain="Steep Hills" Chance="0.01" />
  </MapResource>
  <MapResource ID="Tin And Copper Deposit" IconName="Resources\TinAndCopperBoost" HighlightIcon="Resources\TinAndCopperBoost" Use="ProductionBoost" BoostTradeItem="Bronze" Value="100">
    <Placement Terrain="Steep Hills" Chance="0.0022" />
    <Placement Terrain="Mountains" Chance="0.004" />
  </MapResource>
  <MapResource ID="Iron Deposit" IconName="Resources\IronBoost" HighlightIcon="Resources\IronBoost" Use="ProductionBoost" BoostTradeItem="Iron" Value="90">
    <Placement Terrain="Steep Hills" Chance="0.0015" />
    <Placement Terrain="Mountains" Chance="0.006" />
  </MapResource>

  <MapResource ID="Gold" IconName="G_Icon_Resource_Gold_01" HighlightIcon="G_Icon_Resource_Gold_01_Active" Use="Money" Value="500">
    <DotColor R="255" G="0" B="255" />
    <Placement Terrain="Mountains" Climate="Northern China" Chance="0.04" />
    <Placement Terrain="Mountains" Climate="Southern China" Chance="0.05" />
    <Placement Terrain="Mountains" Climate="Western China" Chance="0.06" />
    <Placement Terrain="Mountains" Climate="Central Asia" Chance="0.07" />
    <Placement Terrain="Mountains" Climate="Gobi Desert" Chance="0.08" />
  </MapResource>
  <MapResource ID="Jade" IconName="G_Icon_Resource_Jade_01" HighlightIcon="G_Icon_Resource_Jade_01_Active" Use="Other">
    <DotColor R="255" G="0" B="255" />
    <Placement Terrain="Mountains" Climate="Northern China" Chance="0.07" />
    <Placement Terrain="Mountains" Climate="Southern China" Chance="0.06" />
    <Placement Terrain="Mountains" Climate="Western China" Chance="0.05" />
    <Placement Terrain="Mountains" Climate="Central Asia" Chance="0.04" />
    <Placement Terrain="Mountains" Climate="Gobi Desert" Chance="0.03" />
  </MapResource>
  <MapResource ID="Kaolinite" IconName="G_Icon_Resource_WhiteClay_01" HighlightIcon="G_Icon_Resource_WhiteClay_01_Active" Use="ProductionBoost" BoostTradeItem="Ceramics" Value="150">
    <Placement Terrain="Sand" Climate="Northern China" Chance="0.02" />
    <Placement Terrain="Sand" Climate="Southern China" Chance="0.0175" />
    <Placement Terrain="Sand" Climate="Western China" Chance="0.015" />
    <Placement Terrain="Sand" Climate="Central Asia" Chance="0.0045" />
    <Placement Terrain="Sand" Climate="Gobi Desert" Chance="0.0023" />
    <Placement Terrain="Dry Plain" Climate="Northern China" Chance="0.02" />
    <Placement Terrain="Dry Plain" Climate="Southern China" Chance="0.0175" />
    <Placement Terrain="Dry Plain" Climate="Western China" Chance="0.015" />
    <Placement Terrain="Dry Plain" Climate="Central Asia" Chance="0.005" />
    <Placement Terrain="Dry Plain" Climate="Gobi Desert" Chance="0.0026" />
  </MapResource>
</Root>
