=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Rules.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="OrientalEmpires" xmlns:oe="OrientalEmpires" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="FloatProperty">
    <xs:attribute name="Name" type="xs:string" use="required"/>
    <xs:attribute name="Value" type ="xs:float" use="required"/>
  </xs:complexType>
  <xs:complexType name="IntProperty">
    <xs:attribute name="Name" type="xs:string" use="required"/>
    <xs:attribute name="Value" type ="xs:int" use="required"/>
  </xs:complexType>
  <xs:complexType name="StringProperty">
    <xs:attribute name="Name" type="xs:string" use="required"/>
    <xs:attribute name="Value" type ="xs:string" use="required"/>
  </xs:complexType>

  <xs:element name="Rules">

    <xs:complexType>
      <xs:sequence>
        <!-- List of Terrain classes -->
        <xs:element name="TerrainClass" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="Name" type ="xs:ID" use ="required"/>
            <xs:attribute name="Water" type="xs:boolean" use ="optional"/>
            <xs:attribute name="CapabilityNeededToPass" type="xs:string" use ="optional"/>
          </xs:complexType>
        </xs:element>
        
        <!-- List of Movement types -->
        <xs:element name="MovementClass" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Impassable" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="Class" type="xs:IDREF" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Terrain" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="Class" type="xs:IDREF" use="required"/>
                  <xs:attribute name="Points" type="xs:integer" use="required"/>
                  <xs:attribute name="CrossingOnly" type="xs:boolean" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string" use="required"/>
            <xs:attribute name="MovePoints" type ="xs:nonNegativeInteger" use="required"/>
            <xs:attribute name="Naval" type="xs:boolean" use="required"/>
            <xs:attribute name="RoadModifier" type="xs:float" use="optional"/>
            <xs:attribute name="Base" type="xs:string" use="optional"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="TerrainCombatEffectClass" maxOccurs ="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="TerrainEffect" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="MoveClass" type="xs:string" use="required"/>
                  <xs:attribute name="AttackModifier" type="xs:float" use="required"/>
                  <xs:attribute name="DefenseModifier" type="xs:float" use="required"/>
                  <xs:attribute name="Charge" type="xs:boolean" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ID" type="xs:string" use="required"/>
            <xs:attribute name="WadingModifier" type="xs:float" use="required"/>
          </xs:complexType>  
        </xs:element>
        
        <xs:element name ="WeaponClass" maxOccurs ="unbounded">
          <xs:complexType>
            <xs:attribute name ="Name" type="xs:string" use ="required"/>
            <xs:attribute name ="Attack" type="xs:int" use ="required"/>
            <xs:attribute name ="Defense" type ="xs:int" use ="required"/>
            <xs:attribute name="APLevel" type ="xs:int" use="optional"/>
            <xs:attribute name="CavDefenceLevel" type ="xs:int" use="optional"/>
            <xs:attribute name="CavAttackLevel" type ="xs:int" use="optional"/>
            <xs:attribute name="FootAttackLevel" type ="xs:int" use="optional"/>
            <xs:attribute name="Metallic" type ="xs:float" use="optional"/>
            <xs:attribute name="Blade" type ="xs:boolean" use="optional"/>
            <xs:attribute name="TerrainCombatClass" type ="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="CombatSkillClass" maxOccurs ="unbounded">
          <xs:complexType>
            <xs:attribute name ="Name" type="xs:string" use ="required"/>
            <xs:attribute name ="Attack" type="xs:int" use ="required"/>
            <xs:attribute name ="Defense" type ="xs:int" use ="required"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="ArmorClass" maxOccurs ="unbounded">
          <xs:complexType>
            <xs:attribute name ="Name" type="xs:string" use ="required"/>
            <xs:attribute name ="Defense" type ="xs:int" use ="required"/>
            <xs:attribute name ="HorseDefense" type ="xs:int" use ="optional"/>
            <xs:attribute name="Metallic" type ="xs:float" use="optional"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="ShieldClass" maxOccurs ="unbounded">
          <xs:complexType>
            <xs:attribute name ="Name" type="xs:string" use ="required"/>
            <xs:attribute name ="Defense" type ="xs:int" use ="required"/>
            <xs:attribute name="Metallic" type ="xs:float" use="optional"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="MoraleClass" maxOccurs ="unbounded">
          <xs:complexType>
            <xs:attribute name ="Name" type="xs:string" use ="required"/>
            <xs:attribute name ="Morale" type="xs:int" use ="required"/>
          </xs:complexType>
        </xs:element>

        <xs:element name ="RecruitmentPool" maxOccurs ="unbounded">
          <xs:complexType>
            <xs:attribute name ="ID" type="xs:string" use ="required"/>
            <xs:attribute name ="RegenTime" type="xs:nonNegativeInteger" use ="required"/>
            <xs:attribute name ="Population" type="xs:string" use ="optional"/>
            <xs:attribute name ="AmountPerPop" type="xs:float" use ="optional"/>
            <xs:attribute name ="Min" type="xs:nonNegativeInteger" use ="optional"/>
            <xs:attribute name ="Max" type="xs:positiveInteger" use ="optional"/>
            <xs:attribute name ="IsNoble" type="xs:boolean" use ="optional"/>
            <xs:attribute name ="IsPeasant" type="xs:boolean" use ="optional"/>
            <xs:attribute name ="IsTribal" type="xs:boolean" use ="optional"/>
            <xs:attribute name ="SplitWithTribal" type="xs:boolean" use ="optional"/>
            <xs:attribute name ="DisbandedUnitReturn" type="xs:boolean" use ="optional"/>
            <xs:attribute name ="ReplenishAnywhere" type="xs:boolean" use ="optional"/>
            <xs:attribute name ="Naval" type="xs:boolean" use ="optional"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="GeneralRules" minOccurs="0">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element name="FProperty" type="oe:FloatProperty"/>
              <xs:element name="SProperty" type="oe:StringProperty"/>
              <xs:element name="IProperty" type="oe:IntProperty"/>
            </xs:choice>
          </xs:complexType>
        </xs:element>
        <xs:element name="SettlementRules" minOccurs="0">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element name="FProperty" type="oe:FloatProperty"/>
              <xs:element name="SProperty" type="oe:StringProperty"/>
              <xs:element name="IProperty" type="oe:IntProperty"/>
            </xs:choice>
          </xs:complexType>
        </xs:element>
        <xs:element name="CombatRules" minOccurs="0">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element name="FProperty" type="oe:FloatProperty"/>
              <xs:element name="SProperty" type="oe:StringProperty"/>
              <xs:element name="IProperty" type="oe:IntProperty"/>
            </xs:choice>
          </xs:complexType>
        </xs:element>
        <xs:element name="MoraleRules" minOccurs="0">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element name="FProperty" type="oe:FloatProperty"/>
              <xs:element name="SProperty" type="oe:StringProperty"/>
              <xs:element name="IProperty" type="oe:IntProperty"/>
            </xs:choice>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>        
  </xs:element>

</xs:schema>

=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Rules.xml
<?xml version="1.0" encoding="utf-8"?>
<Rules xmlns="OrientalEmpires" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="OrientalEmpires Rules.xsd">

  <!-- MOVEMENT RULES ////////////////////////////////////////////////////////-->
  <!-- Terrain Classes -->
  <!-- Land -->
  <TerrainClass Name="FlatGround" />
  <TerrainClass Name="SoftGround" />
  <TerrainClass Name="RoughGround" />
  <TerrainClass Name="GentleHills" />
  <TerrainClass Name="SteepHills" />
  <TerrainClass Name="Mountains" />
  <TerrainClass Name="Forest" />
  <TerrainClass Name="Impassable" />

  <!-- Water -->
  <TerrainClass Name="Ocean" Water="true" CapabilityNeededToPass="Oceanfaring" />
  <TerrainClass Name="Sea" Water="true" CapabilityNeededToPass="Seafaring" />
  <TerrainClass Name="Coastal" Water="true" />
  <TerrainClass Name="NavigableRiver" Water="true" />
  <TerrainClass Name="UnnavigableRiver" Water="true" />

  <!-- Movement Classes -->
  <!-- All terrain classes cost 1 move point unless otherwise specified -->
  <!-- Water terrain is impassable to non naval and land is impassable to naval unless otherwise specified -->
  <!-- Land -->
  <MovementClass Name="BaseLandF" MovePoints="4" Naval="false" RoadModifier="0.66">
    <Impassable Class="Impassable" />
    <Impassable Class="Mountains" />
    <Impassable Class="SteepHills" />
    <Impassable Class="Ocean" />
    <Impassable Class="Sea" />
    <Impassable Class="Coastal" />
    <Impassable Class="UnnavigableRiver" />
    <Terrain Class="NavigableRiver" Points="-1" CrossingOnly="true" />
    <Terrain Class="Forest" Points="-1" CrossingOnly="true" />
  </MovementClass>
  <MovementClass Name="BaseLandF1" MovePoints="4" Naval="false" RoadModifier="0.66">
    <Impassable Class="Impassable" />
    <Impassable Class="Mountains" />
    <Impassable Class="SteepHills" />
    <Impassable Class="Ocean" />
    <Impassable Class="Sea" />
    <Impassable Class="Coastal" />
    <Impassable Class="UnnavigableRiver" />
    <Terrain Class="NavigableRiver" Points="-1" CrossingOnly="true" />
    <Terrain Class="Forest" Points="1" CrossingOnly="true" />
  </MovementClass>
  <MovementClass Name="BaseLand" MovePoints="4" Naval="false" RoadModifier="0.66">
    <Impassable Class="Impassable" />
    <Impassable Class="Mountains" />
    <Impassable Class="SteepHills" />
    <Impassable Class="Ocean" />
    <Impassable Class="Sea" />
    <Impassable Class="Coastal" />
    <Terrain Class="NavigableRiver" Points="-1" CrossingOnly="true" />
    <Terrain Class="UnnavigableRiver" Points="-1" CrossingOnly="true" />
    <Terrain Class="Forest" Points="2" />
  </MovementClass>
  <MovementClass Name="NoForest" MovePoints="4" Naval="false" RoadModifier="0.66">
    <Impassable Class="Impassable" />
    <Impassable Class="Mountains" />
    <Impassable Class="SteepHills" />
    <Impassable Class="Ocean" />
    <Impassable Class="Sea" />
    <Impassable Class="Coastal" />
    <Impassable Class="UnnavigableRiver" />
    <Impassable Class="Forest" />
    <Terrain Class="NavigableRiver" Points="-1" CrossingOnly="true" />
  </MovementClass>
  <MovementClass Name="Garrisson" MovePoints="1" Naval="false" RoadModifier="1">
    <Impassable Class="Impassable" />
    <Impassable Class="Mountains" />
    <Impassable Class="SteepHills" />
    <Impassable Class="Ocean" />
    <Impassable Class="Sea" />
    <Impassable Class="Coastal" />
    <Impassable Class="UnnavigableRiver" />
    <Impassable Class="Forest" />
    <Impassable Class="NavigableRiver" />
    <Impassable Class="SoftGround" />
    <Impassable Class="RoughGround" />
  </MovementClass>
  <MovementClass Name="Tier 1 Infantry" Base="BaseLand" MovePoints="13" Naval="false" RoadModifier="0.66">
    <Terrain Class="SoftGround" Points="11" />
    <Terrain Class="RoughGround" Points="9" />
  </MovementClass>
  <MovementClass Name="Tier 2 Infantry" Base="BaseLand" MovePoints="12" Naval="false" RoadModifier="0.66">
    <Terrain Class="SoftGround" Points="10" />
    <Terrain Class="RoughGround" Points="8" />
  </MovementClass>
  <MovementClass Name="Tier 3 Infantry" Base="BaseLandF" MovePoints="11" Naval="false" RoadModifier="0.66">
    <Terrain Class="SoftGround" Points="9" />
    <Terrain Class="RoughGround" Points="7" />
  </MovementClass>
  <MovementClass Name="Tier 4 Infantry" Base="BaseLandF" MovePoints="10" Naval="false" RoadModifier="0.66">
    <Terrain Class="SoftGround" Points="8" />
    <Terrain Class="RoughGround" Points="6" />
  </MovementClass>
  <MovementClass Name="Tier 5 Infantry" Base="BaseLandF" MovePoints="9" Naval="false" RoadModifier="0.66">
    <Terrain Class="SoftGround" Points="7" />
    <Terrain Class="RoughGround" Points="6" />
  </MovementClass>
  <MovementClass Name="Tier 6 Infantry" Base="BaseLandF" MovePoints="8" Naval="false" RoadModifier="0.66">
    <Terrain Class="SoftGround" Points="6" />
    <Terrain Class="RoughGround" Points="5" />
  </MovementClass>
  <MovementClass Name="Tier 7 Infantry" Base="BaseLandF" MovePoints="7" Naval="false" RoadModifier="0.66">
    <Terrain Class="SoftGround" Points="5" />
    <Terrain Class="RoughGround" Points="4" />
  </MovementClass>
  <MovementClass Name="Tier 1 Cavalry" Base="BaseLandF1" MovePoints="15" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="13" />
    <Terrain Class="RoughGround" Points="11" />
  </MovementClass>
  <MovementClass Name="Tier 2 Cavalry" Base="BaseLandF1" MovePoints="14" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="12" />
    <Terrain Class="RoughGround" Points="10" />
  </MovementClass>
  <MovementClass Name="Tier 3 Cavalry" Base="BaseLandF" MovePoints="13" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="11" />
    <Terrain Class="RoughGround" Points="9" />
  </MovementClass>
  <MovementClass Name="Tier 4 Cavalry" Base="NoForest" MovePoints="12" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="10" />
    <Terrain Class="RoughGround" Points="8" />
  </MovementClass>
  <MovementClass Name="Tier 5 Cavalry" Base="NoForest" MovePoints="11" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="9" />
    <Terrain Class="RoughGround" Points="7" />
  </MovementClass>
  <MovementClass Name="Tier 6 Cavalry" Base="NoForest" MovePoints="10" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="8" />
    <Terrain Class="RoughGround" Points="6" />
  </MovementClass>
  <MovementClass Name="Tier 7 Cavalry" Base="NoForest" MovePoints="9" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="7" />
    <Terrain Class="RoughGround" Points="4" />
  </MovementClass>
  <MovementClass Name="Tier 1 Chariot" Base="NoForest" MovePoints="16" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="7" />
    <Terrain Class="RoughGround" Points="8" />
  </MovementClass>
  <MovementClass Name="Tier 1 Chariot" Base="NoForest" MovePoints="15" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="6" />
    <Terrain Class="RoughGround" Points="7" />
  </MovementClass>
  <MovementClass Name="Tier 3 Chariot" Base="NoForest" MovePoints="14" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="5" />
    <Terrain Class="RoughGround" Points="6" />
  </MovementClass>
  <MovementClass Name="Tier 4 Chariot" Base="NoForest" MovePoints="13" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="4" />
    <Terrain Class="RoughGround" Points="5" />
  </MovementClass>
  <MovementClass Name="Tier 5 Chariot" Base="NoForest" MovePoints="12" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="3" />
    <Terrain Class="RoughGround" Points="4" />
  </MovementClass>
  <MovementClass Name="Tier 6 Chariot" Base="NoForest" MovePoints="10" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="2" />
    <Terrain Class="RoughGround" Points="3" />
  </MovementClass>
  <MovementClass Name="Tier 7 Chariot" Base="NoForest" MovePoints="9" Naval="false" RoadModifier="0.8">
    <Terrain Class="SoftGround" Points="1" />
    <Terrain Class="RoughGround" Points="2" />
  </MovementClass>
  <MovementClass Name="Baggage Train" Base="NoForest" MovePoints="12" Naval="false" RoadModifier="0.66">
    <Terrain Class="SoftGround" Points="10" />
    <Terrain Class="RoughGround" Points="8" />
  </MovementClass>
  <MovementClass Name="Settler" Base="BaseLand" MovePoints="16" Naval="false" RoadModifier="0.66">
    <Terrain Class="SoftGround" Points="14" />
    <Terrain Class="RoughGround" Points="12" />
  </MovementClass>
  <!--Base-->
  <MovementClass Name="Infantry" Base="BaseLand" MovePoints="4" Naval="false" RoadModifier="0.66">
    <Terrain Class="SoftGround" Points="2" />
  </MovementClass>
  <MovementClass Name="Light Infantry" Base="Infantry" MovePoints="5" Naval="false" RoadModifier="0.66">
    <Terrain Class="Forest" Points="1" />
    <Terrain Class="SoftGround" Points="1" />
  </MovementClass>
  <MovementClass Name="Light Cavalry" Base="BaseLand" MovePoints="8" Naval="false" RoadModifier="0.8">
    <Terrain Class="Forest" Points="6" />
    <Terrain Class="SoftGround" Points="6" />
  </MovementClass>
  <MovementClass Name="Scout Cavalry" Base="BaseLand" MovePoints="10" Naval="false" RoadModifier="0.8">
    <Terrain Class="Forest" Points="3" />
    <Terrain Class="SoftGround" Points="5" />
  </MovementClass>
  <MovementClass Name="Heavy Cavalry" Base="BaseLand" MovePoints="6" Naval="false" RoadModifier="0.8">
    <Terrain Class="Forest" Points="4" />
    <Terrain Class="SoftGround" Points="4" />
  </MovementClass>
  <MovementClass Name="Chariot" Base="BaseLand" MovePoints="6" Naval="false" RoadModifier="0.8">
    <Terrain Class="Forest" Points="6" />
