=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Technology.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="OrientalEmpires" xmlns:oe="OrientalEmpires" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:include schemaLocation="Requirement.xsd"/>
  <xs:include schemaLocation="OECommon.xsd"/>

  <!-- Enumeration of areas -->
  <xs:simpleType name="TechArea">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Thought"/>
      <xs:enumeration value="Knowledge"/>
      <xs:enumeration value="Craft"/>
      <xs:enumeration value="Power"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="LevelData">
    <xs:attribute name="Level" type="xs:nonNegativeInteger" use="required"/>
    <xs:attribute name="Turns" type="xs:nonNegativeInteger" use="required"/>
    <xs:attribute name="Era" type="xs:nonNegativeInteger" use="optional"/>
  </xs:complexType>
  
  <!-- Entry for an individual item-->
  <xs:complexType name="TechnologyItem">
    <xs:sequence>
      <xs:element name ="Description" minOccurs="0"></xs:element>
      <xs:element name="Data">
        <xs:complexType>
          <xs:attribute name="Tech" type ="oe:TechArea" use ="required"/>
          <xs:attribute name="Area" type ="oe:TechEdictArea" use ="required"/>
          <xs:attribute name="Level" type="xs:nonNegativeInteger" use ="required"/>
          <xs:attribute name="Difficulty" type="xs:float" use ="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name ="StaticRequirements" type ="oe:RequirementList" minOccurs ="0"/>
      <xs:element name ="Requirements" type ="oe:RequirementList" minOccurs ="0"/>
      <xs:element name ="Prerequisite" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name ="Item" type="xs:string" use ="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Capability" minOccurs ="0" maxOccurs ="unbounded">
        <xs:complexType>
          <xs:attribute name ="Name" type="xs:string" use="required"/>
          <xs:attribute name ="Level" type="xs:int" use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="CustomGameTech" minOccurs="0">
        <xs:complexType>
          <xs:attribute name="FactionTag" type="xs:string" use="optional"/>
          <xs:attribute name="Condition" type="xs:boolean" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name ="ID" type ="xs:string" use="required"/>
    <xs:attribute name ="TranslationTag" type ="xs:string" use="optional"/>
    <xs:attribute name="Icon" type ="xs:string" use ="required"/>
  </xs:complexType>

 <!-- Modding Elements //////////////////////////////////////////////// -->

  <xs:complexType name="DropTechType">
    <xs:attribute name="ID" type="xs:string" use="required"/>
  </xs:complexType>
  
  <!--///////////////////////////////////////////////////////////////// -->

  <xs:element name ="TechnologyItems">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="LevelData" type="oe:LevelData" maxOccurs="unbounded"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element name="Item" type ="oe:TechnologyItem" maxOccurs ="unbounded"/>
          <xs:element name="Drop" type="oe:DropTechType"/>
          <xs:element name="Replace" type="oe:TechnologyItem"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JMonkeyFan/Oriental-Empires-Reimagined/XML/Technology.xml
<?xml version="1.0" encoding="utf-8"?>
<TechnologyItems xmlns="OrientalEmpires" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="OrientalEmpires Technology.xsd">
  <!-- Balance -->
  <LevelData Level="0" Turns="8" Era="0" />
  <LevelData Level="1" Turns="9" />
  <LevelData Level="2" Turns="10" />
  <LevelData Level="3" Turns="11" />
  <LevelData Level="4" Turns="12" Era="1" />
  <LevelData Level="5" Turns="13" />
  <LevelData Level="6" Turns="14" />
  <LevelData Level="7" Turns="15" Era="2" />
  <LevelData Level="8" Turns="16" />
  <LevelData Level="9" Turns="16" />
  <LevelData Level="10" Turns="16" />
  <LevelData Level="11" Turns="16" />
  <LevelData Level="12" Turns="16" />
  <!-- Combat Related -->
  <!-- <Capability Name="Infantry Skill" Level="1" />
    <Capability Name="Sword Skill" Level="1" />
    <Capability Name="Bow Skill" Level="1" />
    <Capability Name="Chariot Skill" Level="1" />
    <Capability Name="Cavalry Skill" Level="1" />
    <Capability Name="CombatAdvantage" Level="1" />
    <Capability Name="Battle Healing" Level="1" />
    <Capability Name="Melee Attack" Level="1" />
    <Capability Name="Melee Defense" Level="1" />
    <Capability Name="Capture Tech" Level="1" /> -->
  <!-- Character Related -->
  <!-- <Capability Name="Character Armor" Level="1" />
    <Capability Name="NewLeaderEnergy" Level="1" />
    <Capability Name="NewLeaderVirtue" Level="1" /> -->
  <!-- Economy Related -->
  <!-- <Capability Name="CeramicsTradeValue" Level="1" />
    <Capability Name="BronzeTradeValue" Level="1" />
    <Capability Name="IronTradeValue" Level="1" />
    <Capability Name="SilkTradeValue" Level="1" />
    <Capability Name="CeramicsTradeValue" Level="1" />
    <Capability Name="Increase Trade" Level="1" />
    <Capability Name="AgriculturalProduction" Level="1" /> -->
  <!-- Building Related -->
  <!-- <Capability Name="Boost Military" Level="1" /> -->
  <!-- <Capability Name="Boost Naval" Level="1" /> -->
  <!-- <Capability Name="Boost Agriculture" Level="1" /> -->
  <!-- <Capability Name="Boost Economy" Level="1" /> -->
  <!-- <Capability Name="Boost Authority" Level="1" /> -->
  <!-- <Capability Name="Boost Culture" Level="1" /> -->
  <!-- <Capability Name="Boost Misc" Level="1" /> -->

  <!-- Happiness/Authority Related -->
  <!-- <Capability Name="Noble Happiness" Level="1" />
    <Capability Name="Peasant Happiness" Level="1" />
    <Capability Name="Noble Unrest" Level="1" />
    <Capability Name="Peasant Unrest" Level="1" />
    <Capability Name="Battle Healing" Level="1" />
    <Capability Name="Capture Tech" Level="1" /> -->
  <!-- Tech Related -->
  <!-- <Capability Name="Boost Power" Level="1" /> -->
  <!-- <Capability Name="Boost Craft" Level="1" /> -->
  <!-- <Capability Name="Boost Thought" Level="1" /> -->
  <!-- <Capability Name="Boost Knowledge" Level="1" /> -->
  <!-- Other
    <Capability Name="Authority" Level="1" />
    <Capability Name="Culture" Level="1" /> -->
  <!--Techs -->
  <!--Knowledge: 47-->
  <!--Thought: 54-->
  <!--Craft: 54-->
  <!--Power: 62 -->
  <!-- Military Authority Total: 129 -->
  <!-- Economy  Total: 89 -->
  <!-- Authority Authority Total: 140 -->
  <!-- Culture Authority Total: 0 -->
  <!-- Agriculture Totals
    AgricultureProduction: 15 + 28 + 25 = 68%
    BoostAgriculture: 41 + 10 - 6 = 45%
    BoostProduction:  14 + 15 = 29%
  Peasant Happiness: 40
  With Astrology: 40
  With Zoology: 46
  Peasant Unrest with Legalism(no priest king): 12
  Peasant Unrest With (no priest king)Agressive Legalism: 20  
   Noble Happiness: 43 with priest king: 51
     Noble unrest base: 16
  Noble Unrest with Legalism(no priest king): 31
  Noble Unrest With (no priest king)Agressive Legalism: 41  
  -->

  <!-- Agriculture 
    Happiness: 
    Peasant: 14
    Tools 
    4X2+12= 15% agricultureproduction  
  4X2+12= 41% Boost Agriculture-->
  <Item ID="Seed Drill" Icon="G_TechIcon_SeedlingTransplantation_01">
    <Data Tech="Craft" Area="Agriculture" Level="1" />
    <Prerequisite Item="Agriculture" />
    <!-- <Capability Name="Peasant Happiness" Level="1" /> -->
    <Capability Name="AgriculturalProduction" Level="2" />
  </Item>
  <!--Reapers -->
  <Item ID="Reaper" Icon="G_TechIcon_IronPlough_01">
    <Data Tech="Craft" Area="Agriculture" Level="2" />
    <Prerequisite Item="Seed Drill" />
    <!-- <Capability Name="Peasant Happiness" Level="1" /> -->
    <Capability Name="AgriculturalProduction" Level="2" />
  </Item>
  <Item ID="Iron Reaper" Icon="G_TechIcon_IronPlough_01">
    <Data Tech="Craft" Area="Agriculture" Level="4" />
    <Prerequisite Item="Reaper" />
    <Prerequisite Item="Iron Casting" />
    <!-- <Capability Name="Peasant Happiness" Level="2" /> -->
    <Capability Name="AgriculturalProduction" Level="2" />
  </Item>
  <!--Ploughs -->
  <Item ID="Plough" Icon="G_TechIcon_IronPlough_01">
    <Data Tech="Craft" Area="Agriculture" Level="3" />
    <Prerequisite Item="Seed Drill" />
    <!-- <Capability Name="Peasant Happiness" Level="1" /> -->
    <Capability Name="AgriculturalProduction" Level="3" />
  </Item>
  <Item ID="Iron Plough" Icon="G_TechIcon_IronPlough_01">
    <Data Tech="Craft" Area="Agriculture" Level="6" />
    <Prerequisite Item="Plough" />
    <Prerequisite Item="Quenching" />
    <!-- <Capability Name="Peasant Happiness" Level="2" /> -->
    <Capability Name="AgriculturalProduction" Level="3" />
  </Item>
  <!-- Quernstones -->
  <Item ID="Saddle Quernstone" Icon="G_TechIcon_BrickFacedWells_01">
    <Data Tech="Craft" Area="Agriculture" Level="6" />
    <Prerequisite Item="Agriculture" />
    <!-- <Capability Name="Peasant Happiness" Level="2" /> -->
    <Capability Name="AgriculturalProduction" Level="3" />
  </Item>
  <Item ID="Rotary Quernstone" Icon="G_TechIcon_BrickFacedWells_01">
    <Data Tech="Craft" Area="Agriculture" Level="7" />
    <Prerequisite Item="Saddle Quernstone" />
    <Capability Name="AgriculturalProduction" Level="3" />
    <!-- <Capability Name="Peasant Happiness" Level="2" /> -->
  </Item>
  <!--Other -->
  <Item ID="Thresher" Icon="G_TechIcon_CropRotation_01">
    <Data Tech="Craft" Area="Agriculture" Level="7" />
    <Prerequisite Item="Crop Rotation" />
    <Prerequisite Item="Brick Faced Wells" />
    <Capability Name="Noble Unrest" Level="1" />
    <Capability Name="AgriculturalProduction" Level="3" />
    <!-- <Capability Name="Peasant Happiness" Level="3" /> -->
  </Item>
  <!-- Agriculture Improvements 
    noble happiness: 10
ProductionBoost: 14
AgriculturalProduction: 28
Boost Agriculture: 10 -->
  <Item ID="Flood Control" Icon="G_TechIcon_FloodControl_01">
    <Data Tech="Power" Area="Agriculture" Level="3" />
    <StaticRequirements>
      <FactionTag Tag="Japan Tech" Condition="false" />
    </StaticRequirements>
    <Prerequisite Item="Agriculture" />
    <!-- <Capability Name="Noble Happiness" Level="2" /> -->
    <Capability Name="Boost Economy" Level="2" />
    <Capability Name="AgriculturalProduction" Level="4" />
    <Capability Name="Boost Agriculture" Level="4" />
  </Item>
  <Item ID="Marsh Drainage" Icon="G_TechIcon_MarshDrainage_01">
    <Data Tech="Power" Area="Agriculture" Level="5" />
    <Prerequisite Item="Flood Control" />
    <!-- <Capability Name="Noble Happiness" Level="3" /> -->
    <Capability Name="Boost Economy" Level="3" />
    <Capability Name="AgriculturalProduction" Level="2" />
    <Capability Name="Boost Agriculture" Level="5" />
  </Item>
  <Item ID="Terracing" Icon="G_TechIcon_Terracing_01">
    <Data Tech="Power" Area="Agriculture" Level="4" />
    <Prerequisite Item="Flood Control" />
    <!-- <Capability Name="Noble Happiness" Level="3" /> -->
    <Capability Name="Boost Economy" Level="4" />
    <Capability Name="AgriculturalProduction" Level="2" />
    <Capability Name="Boost Agriculture" Level="4" />
  </Item>
  <Item ID="Irrigation" Icon="G_TechIcon_Irrigation_01">
    <Data Tech="Power" Area="Agriculture" Level="4" />
    <Requirements>
      <RequireEither>
        <Tech Item="Iron Plough" />
        <Tech Item="Thresher" />
      </RequireEither>
      <RequireEither>
        <Tech Item="Marsh Drainage" />
        <Tech Item="Terracing" />
      </RequireEither>
    </Requirements>
    <Prerequisite Item="Agriculture" />
    <!-- <Capability Name="Boost Power" Level="12" /> -->
    <!-- <Capability Name="Noble Happiness" Level="2" /> -->
    <Capability Name="AgriculturalProduction" Level="4" />
    <Capability Name="Boost Agriculture" Level="5" />
  </Item>
  <!-- Agriculture Wells 
    noble happiness: 5
    peasant happiness: 3
ProductionBoost: 15-->
  <Item ID="Wells" Icon="G_TechIcon_BrickFacedWells_01">
    <Data Tech="Craft" Area="Agriculture" Level="4" />
    <Prerequisite Item="Flood Control" />
    <Prerequisite Item="Ceramic Roof Tiles" />
    <!-- <Capability Name="Peasant Happiness" Level="1" /> -->
    <!-- <Capability Name="Noble Happiness" Level="2" /> -->
    <Capability Name="Boost Economy" Level="5" />
    <Capability Name="AgriculturalProduction" Level="5" />
  </Item>
  <Item ID="Brick Faced Wells" Icon="G_TechIcon_BrickFacedWells_01">
    <Data Tech="Craft" Area="Agriculture" Level="6" />
    <Prerequisite Item="Wells" />
    <!-- <Capability Name="Peasant Happiness" Level="1" /> -->
    <!-- <Capability Name="Noble Happiness" Level="2" /> -->
    <Capability Name="Boost Economy" Level="5" />
    <Capability Name="AgriculturalProduction" Level="5" />
  </Item>
  <!-- Agriculture Ideas
    noble happiness: 5
    peasant happiness: 3
  AgricultureProduction: 25
  BoostAgriculture: -6-->
  <Item ID="Seedling Transplantation" Icon="G_TechIcon_SeedlingTransplantation_01">
    <Data Tech="Knowledge" Area="Agriculture" Level="6" />
    <Prerequisite Item="Irrigation" />
